<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Paradise.Rendering.Browser.Test</AssemblyName>
    <RootNamespace>Paradise.Rendering.Browser.Test</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Paradise.Rendering.Browser\Paradise.Rendering.Browser.csproj" />
  </ItemGroup>
</Project>
