using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Paradise.Authoring.Generators;

/// <summary>
/// Emits an <c>IAuthoredComponentRegistry</c> for the compiling assembly: component id → the record
/// it deserializes into.
///
/// This is the LOADING half of <c>[Authored]</c>. Without it, filling an instance from an exported
/// payload is a hand-written accessor per component, naming both the id and the JsonTypeInfo — and
/// forgetting one means a component that authors, exports, and is then silently never read.
///
/// Only emitted when the assembly declares <c>[AuthoredJsonContext]</c>, because the generated code
/// has to name a context: reflection is out (it breaks Godot's hot-reload, and does not trim), and
/// this generator cannot OBSERVE what System.Text.Json's generator emits. It can REFERENCE it —
/// generated sources compile together, so <c>Ctx.Default.Record</c> resolves even though neither
/// generator saw the other. That was verified with a throwaway spike before this existed, because
/// the opposite limitation is exactly what made generating Godot's inspector impossible.
/// </summary>
[Generator]
public sealed class AuthoredRegistryGenerator : IIncrementalGenerator
{
    private const string ContextAttribute = "Paradise.Authoring.AuthoredJsonContextAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var authored = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AuthoredModel.AuthoredAttribute,
                predicate: static (node, _) => true,
                transform: static (ctx, _) => ctx.TargetSymbol is INamedTypeSymbol type
                    ? AuthoredModel.ReadIdentity(type)
                    : null)
            .Where(static x => x is not null)
            .Collect();

        var settings = context.CompilationProvider
            .Combine(context.AnalyzerConfigOptionsProvider)
            .Select(static (pair, _) =>
            {
                pair.Right.GlobalOptions.TryGetValue("build_property.RootNamespace", out var root);
                var ns = string.IsNullOrWhiteSpace(root) ? pair.Left.AssemblyName : root;

                string? contextName = null;
                foreach (var a in pair.Left.Assembly.GetAttributes())
                {
                    if (a.AttributeClass?.ToDisplayString() == ContextAttribute &&
                        a.ConstructorArguments.Length == 1 &&
                        a.ConstructorArguments[0].Value is INamedTypeSymbol type)
                    {
                        contextName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    }
                }
                return (Namespace: AuthoringSchemaGenerator.Sanitize(ns), Context: contextName);
            });

        context.RegisterSourceOutput(
            authored.Combine(settings),
            static (ctx, pair) => Emit(ctx, pair.Left!, pair.Right.Namespace, pair.Right.Context));
    }

    private static void Emit(
        SourceProductionContext context,
        ImmutableArray<AuthoredIdentity?> types,
        string namespaceName,
        string? contextName)
    {
        if (contextName is null)
        {
            // No context declared: this assembly publishes a schema for editors and never loads
            // payloads back. Emitting a registry it cannot fill would be worse than none.
            return;
        }

        var present = types.Where(t => t is not null).Select(t => t!)
            .OrderBy(t => t.ComponentId, System.StringComparer.Ordinal)
            .ToList();
        if (present.Count == 0)
        {
            return;
        }

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.Append("namespace ").Append(namespaceName).AppendLine(";");
        source.AppendLine();
        source.AppendLine("/// <summary>Materializes this assembly's [Authored] records from exported payloads.");
        source.AppendLine("/// Generated from every [Authored] type; do not edit.</summary>");
        source.AppendLine("public sealed class AuthoredComponents : global::Paradise.Authoring.IAuthoredComponentRegistry");
        source.AppendLine("{");
        source.AppendLine("    /// <summary>A shared instance: the registry is stateless.</summary>");
        source.AppendLine("    public static readonly AuthoredComponents Default = new();");
        source.AppendLine();
        source.AppendLine("    private static readonly string[] Ids =");
        source.AppendLine("    [");
        foreach (var type in present)
        {
            source.Append("        ").Append(Quote(type.ComponentId)).AppendLine(",");
        }
        source.AppendLine("    ];");
        source.AppendLine();
        source.AppendLine("    public global::System.Collections.Generic.IReadOnlyCollection<string> ComponentIds => Ids;");
        source.AppendLine();
        source.AppendLine("    public bool TryRead(string componentId, global::System.Text.Json.JsonElement data, out object? component)");
        source.AppendLine("    {");
        source.AppendLine("        switch (componentId)");
        source.AppendLine("        {");
        foreach (var type in present)
        {
            source.Append("            case ").Append(Quote(type.ComponentId)).AppendLine(":");
            source.Append("                component = global::System.Text.Json.JsonSerializer.Deserialize(data, ")
                  .Append(contextName).Append(".Default.").Append(type.TypeName).AppendLine(");");
            source.AppendLine("                return true;");
        }
        source.AppendLine("            default:");
        source.AppendLine("                component = null;");
        source.AppendLine("                return false;");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("}");

        context.AddSource("AuthoredComponents.g.cs", source.ToString());
    }

    private static string Quote(string value) => "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
