<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Paradise.Assets.Pipeline.Test</AssemblyName>
    <RootNamespace>Paradise.Assets.Pipeline.Test</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <Nullable>enable</Nullable>
    <TomlynIsReflectionEnabledByDefault>false</TomlynIsReflectionEnabledByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
    <PackageReference Include="Zio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Paradise.Assets.Pipeline\Paradise.Assets.Pipeline.csproj" />
  </ItemGroup>
</Project>
