using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Paradise.ECS;

/// <summary>Diagnostic information about stale bits in chunk tag masks.</summary>
/// <remarks>
/// Tag removal leaves conservative chunk-mask bits to avoid rescanning every entity.
/// Stale bits cause extra chunk scans, but row filtering still returns the correct entities.
/// </remarks>
/// <param name="TotalChunks">Total number of chunks analyzed.</param>
/// <param name="ChunksWithStaleBits">Number of chunks that have at least one stale bit.</param>
/// <param name="TotalStaleBits">Total count of stale bits across all chunks.</param>
/// <param name="TotalActualBits">Total count of actual (non-stale) tag bits across all chunks.</param>
public readonly record struct StaleBitStatistics(
    int TotalChunks,
    int ChunksWithStaleBits,
    int TotalStaleBits,
    int TotalActualBits)
{
    /// <summary>Fraction of chunk-mask bits that are stale, or zero when no bits are set.</summary>
    public double StaleBitRatio => TotalStaleBits + TotalActualBits == 0
        ? 0
        : (double)TotalStaleBits / (TotalStaleBits + TotalActualBits);

    /// <summary>Fraction of chunks with stale bits, or zero when there are no chunks.</summary>
    public double ChunksWithStaleBitsRatio => TotalChunks == 0
        ? 0
        : (double)ChunksWithStaleBits / TotalChunks;

    /// <summary>Suggests rebuilding when over half the bits or over a quarter of chunks are stale.</summary>
    public bool SuggestsRebuild => StaleBitRatio > 0.5 || ChunksWithStaleBitsRatio > 0.25;
}

/// <summary>
/// A world wrapper that provides tag support for entities.
/// Tags are stored as a component (EntityTags) that is automatically added to spawned entities.
/// </summary>
/// <typeparam name="TMask">The component mask type implementing IBitSet.</typeparam>
/// <typeparam name="TConfig">The world configuration type.</typeparam>
/// <typeparam name="TEntityTags">The EntityTags component type (generated by TagGenerator).</typeparam>
/// <typeparam name="TTagMask">The tag mask type (generated by TagGenerator as TagMask alias).</typeparam>
/// <remarks>
/// TaggedWorld wraps a standard World and adds tag-specific APIs.
/// Tags are stored in a per-entity bitmask component, enabling O(1) tag operations
/// without archetype changes.
/// </remarks>
public sealed class TaggedWorld<TMask, TConfig, TEntityTags, TTagMask> : IWorld<TMask, TConfig>, ICommandExtensionSink
    where TMask : unmanaged, IBitSet<TMask>
    where TConfig : IConfig, new()
    where TEntityTags : unmanaged, IComponent, IEntityTags<TTagMask>
    where TTagMask : unmanaged, IBitSet<TTagMask>
{
    private readonly World<TMask, TConfig> _world;

    /// <summary>
    /// Creates a new TaggedWorld with externally provided subsystems.
    /// The caller is responsible for disposing the provided resources.
    /// </summary>
    /// <param name="config">The configuration instance with runtime settings.</param>
    /// <param name="chunkManager">The chunk manager for memory allocation.</param>
    /// <param name="sharedMetadata">The shared archetype metadata.</param>
    /// <remarks>Tag masks occupy each chunk's reserved tail, so <c>World.CopyFrom</c> carries them with entity data.</remarks>
    public TaggedWorld(
        TConfig config,
        ChunkManager chunkManager,
        SharedArchetypeMetadata<TMask, TConfig> sharedMetadata)
    {
        _world = new World<TMask, TConfig>(config, sharedMetadata, chunkManager);
    }

    /// <summary>The underlying World instance.</summary>
    public World<TMask, TConfig> World => _world;

    public IEntityManager EntityManager => _world.EntityManager;

    /// <summary>The archetype registry for this world.</summary>
    public ArchetypeRegistry<TMask, TConfig> ArchetypeRegistry => _world.ArchetypeRegistry;

    /// <summary>The chunk manager for memory allocation and chunk access.</summary>
    public ChunkManager ChunkManager => _world.ChunkManager;

    /// <inheritdoc/>
    public WorldEventStore Events => _world.Events;

    /// <inheritdoc/>
    public EntityIdAllocator EntityIdAllocator => _world.EntityIdAllocator;

    /// <summary>The current number of live entities.</summary>
    public int EntityCount => _world.EntityCount;

    /// <summary>Spawns a new entity with the EntityTags component automatically added.</summary>
    /// <returns>The newly created entity.</returns>
    public Entity Spawn()
    {
        var entity = _world.Spawn();
        _world.AddComponent<TEntityTags>(entity);
        return entity;
    }

    /// <summary>Despawns an entity, removing it from the world.</summary>
    /// <param name="entity">The entity to despawn.</param>
    /// <returns>True if the entity was despawned; false if it was already dead.</returns>
    /// <remarks>
    /// The chunk tag mask is not recomputed immediately (sticky mask optimization).
    /// Call <see cref="RebuildChunkMasks"/> to clean up stale bits if needed.
    /// </remarks>
    public bool Despawn(Entity entity)
    {
        if (!_world.IsAlive(entity))
            return false;

        CoverSwapVictim(entity);
        _world.Despawn(entity);
        return true;
    }

    /// <summary>
    /// Cover, in advance, the tags of whichever entity a despawn is about to drag into this one's
    /// slot.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Despawn is a swap-remove: the archetype's LAST entity is moved into the hole. When the hole
    /// is in an earlier chunk that entity crosses chunks, carrying tags the destination has never
    /// seen — and unlike every other move, the entity that moves is not the one the caller named,
    /// so there is nothing to call <see cref="CoverTags"/> on afterwards. Which entity it will be
    /// is the world's business, not this wrapper's.
    /// </para>
    /// <para>
    /// So this covers the whole SOURCE CHUNK's mask instead of one entity's tags — a superset of
    /// whatever moves, which is exactly what a conservative mask is allowed to be. It costs the
    /// destination chunk some bits it may not strictly need (a scan, never a wrong answer) and it
    /// needs no cooperation from the layer below. Done BEFORE the despawn, while both chunks are
    /// still where they are.
    /// </para>
    /// <para>
    /// Nothing to do when the victim is already in the same chunk — the common case, and the reason
    /// a single-chunk archetype hides this defect completely.
    /// </para>
    /// </remarks>
    private void CoverSwapVictim(Entity entity)
    {
        var location = _world.GetLocation(entity);
        var archetype = _world.ArchetypeRegistry.GetById(location.ArchetypeId);
        if (archetype is null || !archetype.Layout.ComponentMask.Get(TEntityTags.TypeId.Value))
            return;

        var (chunkIndex, _) = archetype.GetChunkLocation(location.GlobalIndex);
        int lastChunkIndex = archetype.ChunkCount - 1;
        if (lastChunkIndex <= chunkIndex)
            return;

        var sourceMask = ChunkMask(archetype.GetChunk(lastChunkIndex), archetype.Layout);
        ref var destinationMask = ref ChunkMask(archetype.GetChunk(chunkIndex), archetype.Layout);
        destinationMask = destinationMask.Or(sourceMask);
    }

    /// <inheritdoc/>
    public void SetSystemRunInProgress(bool running) => _world.SetSystemRunInProgress(running);

    /// <summary>
    /// Clears all entities from the world.
    /// Also clears all chunk tag masks.
    /// </summary>
    public void Clear()
    {
        _world.Clear();
    }

    /// <summary>
    /// Computes statistics about stale bits in chunk tag masks.
    /// Use this to monitor whether <see cref="RebuildChunkMasks"/> should be called.
    /// </summary>
    /// <returns>A <see cref="StaleBitStatistics"/> containing diagnostic information.</returns>
    /// <remarks>
    /// <para>
    /// Stale bits occur when tags are removed from entities but the chunk mask retains the bit
    /// (sticky mask optimization). While this doesn't affect correctness, it can degrade query
    /// performance by causing false-positive chunk matches.
    /// </para>
    /// <para>
    /// This operation is O(n) where n is the total number of entities. Use sparingly in
    /// performance-critical code paths.
    /// </para>
    /// </remarks>
    public StaleBitStatistics ComputeStaleBitStatistics()
    {
        int totalChunks = 0;
        int totalStaleBits = 0;
        int totalActualBits = 0;
        int chunksWithStaleBits = 0;

        for (int index = 0; index < _world.Archetypes.Count; index++)
        {
            Archetype<TMask, TConfig>? archetype = _world.Archetypes[index];
            if (archetype is null || !archetype.Layout.ComponentMask.Get(TEntityTags.TypeId.Value))
                continue;

            int chunkCount = archetype.ChunkCount;
            for (int chunkIndex = 0; chunkIndex < chunkCount; chunkIndex++)
            {
                var currentMask = ChunkMask(archetype.GetChunk(chunkIndex), archetype.Layout);
                var actualMask = ComputeActualChunkMask(archetype, chunkIndex);

                int currentBits = currentMask.PopCount();
                int actualBits = actualMask.PopCount();
                int staleBits = currentBits - actualBits;

                totalChunks++;
                totalStaleBits += staleBits;
                totalActualBits += actualBits;
                if (staleBits > 0)
                    chunksWithStaleBits++;
            }
        }

        return new StaleBitStatistics(totalChunks, chunksWithStaleBits, totalStaleBits, totalActualBits);
    }

    /// <summary>
    /// Rebuilds all chunk tag masks by scanning all entities.
    /// Call this to clean up stale bits after tag removals or despawns.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This operation is O(n) where n is the total number of entities.
    /// Best called at natural breakpoints (level transitions, loading screens).
    /// </para>
    /// <para>
    /// <b>Performance Impact of Stale Bits:</b> Stale bits cause tag queries to check chunks
    /// that no longer contain matching entities. For workloads with frequent tag removals,
    /// consider calling this method periodically or when <see cref="ComputeStaleBitStatistics"/>
    /// shows high stale bit counts.
    /// </para>
    /// </remarks>
    public void RebuildChunkMasks()
    {
        // No global clear: every slot lives in the chunk it describes and is overwritten below, so
        // there is nothing to reset first — and nothing belonging to another world to destroy. That
        // hazard was real while the masks lived in a registry shared across worlds.
        // Iterate all archetypes that have EntityTags component
        for (int index = 0; index < _world.Archetypes.Count; index++)
        {
            Archetype<TMask, TConfig>? archetype = _world.Archetypes[index];
            if (archetype is null || !archetype.Layout.ComponentMask.Get(TEntityTags.TypeId.Value))
                continue;

            int chunkCount = archetype.ChunkCount;
            for (int chunkIndex = 0; chunkIndex < chunkCount; chunkIndex++)
            {
                var chunkHandle = archetype.GetChunk(chunkIndex);
                RecomputeChunkMask(chunkHandle, archetype, chunkIndex);
            }
        }
    }

    /// <summary>Checks if an entity is still alive.</summary>
    /// <param name="entity">The entity to check.</param>
    /// <returns>True if the entity is alive.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool IsAlive(Entity entity) => _world.IsAlive(entity);

    /// <summary>Adds a tag to an entity.</summary>
    /// <typeparam name="TTag">The tag type to add.</typeparam>
    /// <param name="entity">The entity to add the tag to.</param>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void AddTag<TTag>(Entity entity) where TTag : ITag
        => AddTag(entity, TTag.TagId.Value);

    private void AddTag(Entity entity, int tagId)
    {
        _world.AssertStructuralChangesAllowed(nameof(AddTag));
        ref var tags = ref _world.GetComponent<TEntityTags>(entity);
        tags.Mask = tags.Mask.Set(tagId);
        ref var chunkMask = ref ChunkMaskOf(entity);
        chunkMask = chunkMask.Or(default(TTagMask).Set(tagId));
    }

    /// <summary>Removes a tag from an entity.</summary>
    /// <typeparam name="TTag">The tag type to remove.</typeparam>
    /// <param name="entity">The entity to remove the tag from.</param>
    /// <remarks>
    /// The chunk tag mask is not recomputed immediately (sticky mask optimization).
    /// This may result in false positives during tag queries, which is safe but may
    /// cause queries to check a few extra entities. Call <see cref="RebuildChunkMasks"/>
    /// to clean up stale bits if needed.
    /// </remarks>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void RemoveTag<TTag>(Entity entity) where TTag : ITag
        => RemoveTag(entity, TTag.TagId.Value);

    private void RemoveTag(Entity entity, int tagId)
    {
        _world.AssertStructuralChangesAllowed(nameof(RemoveTag));
        ref var tags = ref _world.GetComponent<TEntityTags>(entity);
        tags.Mask = tags.Mask.Clear(tagId);
        // Chunk mask not recomputed (sticky mask) - may have stale bits
    }

    /// <inheritdoc/>
    public void PlayExtension(Type opType, Entity entity, ReadOnlySpan<byte> data)
    {
        if (opType == typeof(AddTagOp))
        {
            AddTag(entity, ReadTagId(data));
            return;
        }

        if (opType == typeof(RemoveTagOp))
        {
            RemoveTag(entity, ReadTagId(data));
            return;
        }

        throw new InvalidOperationException($"Unknown command extension '{opType}'.");
    }

    private static int ReadTagId(ReadOnlySpan<byte> data)
    {
        if (data.Length != sizeof(int))
        {
            throw new InvalidOperationException("Tag command payload must be a 4-byte tag id.");
        }

        return MemoryMarshal.Read<int>(data);
    }

    /// <summary>Replaces this world's contents with a copy of <paramref name="source"/>, tags included.</summary>
    /// <param name="source">The world to copy from. Must share this world's SharedArchetypeMetadata.</param>
    /// <remarks>
    /// <para>
    /// The tagged counterpart of <see cref="World{TMask,TConfig}.CopyFrom"/>, and the reason a
    /// tagged world can take part in snapshot execution at all: a host that publishes each step by
    /// copying the stepped world into a pooled twin needs this, and without it referencing
    /// Paradise.ECS.Tag cost a consumer its snapshot loop.
    /// </para>
    /// <para>
    /// <b>Per-entity tags need no special handling.</b> They live in the <c>EntityTags</c>
    /// COMPONENT, which sits in the chunks that <see cref="World{TMask,TConfig}.CopyFrom"/> copies,
    /// so every entity arrives already carrying its mask.
    /// </para>
    /// <para>
    /// <b>Chunk masks do.</b> the per-chunk mask table was keyed by
    /// <c>ChunkHandle.Id</c>, and the copy puts the data in DIFFERENT chunks — so this world's new
    /// chunks arrive with no entries at all. Leaving them that way would not be a slow answer but a
    /// WRONG one: <c>ChunkMayMatch</c> reads a clear bit as proof the chunk holds no such tag, so
    /// an empty mask makes a consumer skip chunks whose entities really are tagged. Whatever this
    /// method does, it cannot do nothing.
    /// </para>
    /// <para>
    /// <b>The masks are COPIED, not recomputed.</b> Source chunk j pairs with destination chunk j —
    /// the archetype ids match through the shared metadata and <c>CopyChunksFrom</c> copies in index
    /// order, which is the same pairing <see cref="SnapshotChunkPairing"/> already relies on. So the
    /// answer is already known and costs O(chunks) to move; recomputing it would re-read every
    /// entity's tag mask, O(entities), on every publish — and a host publishing a snapshot per step
    /// pays that per step.
    /// </para>
    /// <para>
    /// What copying gives up is that stale bits ride along. Masks are sticky —
    /// <see cref="RemoveTag{TTag}"/> clears the entity's bit and leaves the chunk's — so a source
    /// carrying bits no entity has any more hands them to the copy. That is deliberate: it is
    /// faithful (a copy should hold what its source holds), it is safe in the only direction that
    /// matters (an extra bit costs a scan, a missing one costs a correct answer), and recomputing
    /// here would not have fixed the real problem anyway — it would clean the SNAPSHOTS while the
    /// live world, the one systems actually query, kept accumulating. That is what
    /// <see cref="RebuildChunkMasks"/> and <see cref="StaleBitStatistics.SuggestsRebuild"/> are for.
    /// </para>
    /// <para>
    /// <b>Deliberately not <see cref="RebuildChunkMasks"/>.</b> That method CLEARS the registry
    /// first, and under <see cref="SharedTaggedWorld{TMask,TConfig,TEntityTags,TTagMask}"/> the
    /// registry is shared by every world made from one shared — so rebuilding "this world's" masks
    /// that way would erase its siblings' and rebuild only its own. Publishing a snapshot would then
    /// blank the live world's masks on every step. This writes only this world's entries.
    /// </para>
    /// </remarks>
    /// <exception cref="InvalidOperationException">Copying a world to itself, or between worlds
    /// that do not share metadata (both surfaced by the inner world).</exception>
    public void CopyFrom(TaggedWorld<TMask, TConfig, TEntityTags, TTagMask> source)
    {
        ArgumentNullException.ThrowIfNull(source);

        _world.CopyFrom(source._world);
    }

    /// <summary>Checks if an entity has a specific tag.</summary>
    /// <typeparam name="TTag">The tag type to check.</typeparam>
    /// <param name="entity">The entity to check.</param>
    /// <returns>True if the entity has the tag.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool HasTag<TTag>(Entity entity) where TTag : ITag
    {
        ref var tags = ref _world.GetComponent<TEntityTags>(entity);
        return tags.Mask.Get(TTag.TagId);
    }

    /// <summary>
    /// The tag mask of the CHUNK <paramref name="entity"/> lives in: the union of the tags of every
    /// entity in it.
    /// </summary>
    /// <remarks>
    /// A conservative summary, not an exact one. Bits are OR-ed in when a tag is added and left
    /// alone when one is removed (see <see cref="RemoveTag{TTag}"/>), so a set bit means "some
    /// entity here may carry this" and only a clear bit is proof of absence. That asymmetry is what
    /// makes it safe to skip a chunk on a clear bit and never safe to trust a set one.
    /// </remarks>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public TTagMask GetChunkMask(Entity entity) => ChunkMaskOf(entity);

    /// <summary>The full tag mask for an entity.</summary>
    /// <param name="entity">The entity to get tags from.</param>
    /// <returns>The tag mask.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public TTagMask GetTags(Entity entity)
    {
        return _world.GetComponent<TEntityTags>(entity).Mask;
    }

    /// <summary>Sets the full tag mask for an entity.</summary>
    /// <param name="entity">The entity to set tags on.</param>
    /// <param name="tags">The tag mask to set.</param>
    /// <remarks>
    /// When tags are removed, the chunk tag mask is not recomputed (sticky mask optimization).
    /// Call <see cref="RebuildChunkMasks"/> to clean up stale bits if needed.
    /// </remarks>
    public void SetTags(Entity entity, TTagMask tags)
    {
        ref var entityTags = ref _world.GetComponent<TEntityTags>(entity);
        var oldMask = entityTags.Mask;
        entityTags.Mask = tags;

        // Only update chunk mask for added tags (sticky mask optimization)
        var addedTags = tags.AndNot(oldMask); // tags in new but not in old

        if (!addedTags.Equals(default(TTagMask)))
        {
            ref var chunkMask = ref ChunkMaskOf(entity);
            chunkMask = chunkMask.Or(addedTags);
        }
        // Removed tags: chunk mask not recomputed (sticky) - may have stale bits
    }

    /// <summary>A reference to a component on an entity.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public ref T GetComponent<T>(Entity entity) where T : unmanaged, IComponent
        => ref _world.GetComponent<T>(entity);

    /// <inheritdoc/>
    public bool TryGetComponent<T>(Entity entity, out T value) where T : unmanaged, IComponent
        => _world.TryGetComponent(entity, out value);

    /// <inheritdoc/>
    public bool TrySetComponent<T>(Entity entity, T value) where T : unmanaged, IComponent
        => _world.TrySetComponent(entity, value);

    /// <summary>Checks if an entity has a component.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool HasComponent<T>(Entity entity) where T : unmanaged, IComponent
        => _world.HasComponent<T>(entity);

    /// <summary>Adds a component to an entity.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void AddComponent<T>(Entity entity, T value = default) where T : unmanaged, IComponent
    {
        // Changes archetype, so the entity moves to a chunk that knows nothing of its tags.
        _world.AddComponent(entity, value);
        CoverTags(entity);
    }

    /// <summary>Removes a component from an entity.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void RemoveComponent<T>(Entity entity) where T : unmanaged, IComponent
    {
        _world.RemoveComponent<T>(entity);
        CoverTags(entity);
    }

    /// <inheritdoc/>
    public void AddComponentRaw(Entity entity, ComponentId componentId, ReadOnlySpan<byte> data)
    {
        _world.AddComponentRaw(entity, componentId, data);
        CoverTags(entity);
    }

    /// <inheritdoc/>
    public void RemoveComponentRaw(Entity entity, ComponentId componentId)
    {
        _world.RemoveComponentRaw(entity, componentId);
        CoverTags(entity);
    }

    /// <inheritdoc/>
    public void SetComponentRaw(Entity entity, ComponentId componentId, ReadOnlySpan<byte> data)
        => _world.SetComponentRaw(entity, componentId, data);

    /// <inheritdoc/>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public Entity CreateEntity<TBuilder>(TBuilder builder) where TBuilder : unmanaged, IComponentsBuilder
    {
        var wrappedBuilder = new EnsureComponent<TEntityTags, TBuilder> { InnerBuilder = builder };
        var entity = _world.CreateEntity(wrappedBuilder);
        // A builder can carry tags (AddTag composes onto it), so a brand-new entity may already be
        // tagged before its chunk has been told.
        CoverTags(entity);
        return entity;
    }

    /// <inheritdoc/>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public Entity CreateEntity(in TMask mask)
    {
        var entity = _world.CreateEntity(mask.Set(TEntityTags.TypeId));
        // Reused entity slots may carry tags that must reach the chunk mask.
        CoverTags(entity);
        return entity;
    }

    /// <inheritdoc/>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public Entity OverwriteEntity<TBuilder>(Entity entity, TBuilder builder) where TBuilder : unmanaged, IComponentsBuilder
    {
        var wrappedBuilder = new EnsureComponent<TEntityTags, TBuilder> { InnerBuilder = builder };
        var result = _world.OverwriteEntity(entity, wrappedBuilder);
        CoverTags(result);
        return result;
    }

    /// <inheritdoc/>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public Entity AddComponents<TBuilder>(Entity entity, TBuilder builder) where TBuilder : unmanaged, IComponentsBuilder
    {
        var result = _world.AddComponents(entity, builder);
        CoverTags(result);
        return result;
    }

    /// <summary>Adds the entity's tags to its chunk's conservative mask after a structural move.</summary>
    /// <remarks>Missing bits would skip matching entities; stale bits only cause extra scans.</remarks>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void CoverTags(Entity entity)
    {
        if (!_world.HasComponent<TEntityTags>(entity))
            return;

        var tags = _world.GetComponent<TEntityTags>(entity).Mask;
        if (tags.Equals(default(TTagMask)))
            return;

        ref var chunkMask = ref ChunkMaskOf(entity);
        chunkMask = chunkMask.Or(tags);
    }

    /// <summary>A reference to the chunk's tag-mask union in its reserved tail.</summary>
    /// <remarks>Keeping the mask in chunk memory makes it travel with chunk copies.</remarks>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private ref TTagMask ChunkMask(
        ChunkHandle chunk, scoped in ImmutableArchetypeLayout<TMask, TConfig> layout)
    {
        int offset = layout.GetChunkAggregateOffset(TEntityTags.TypeId, _world.TypeInfos);
        return ref _world.ChunkManager.GetBytes(chunk).GetRef<TTagMask>(offset);
    }

    /// <summary>The chunk mask of the chunk <paramref name="entity"/> lives in.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private ref TTagMask ChunkMaskOf(Entity entity)
    {
        var location = _world.GetLocation(entity);
        var archetype = _world.ArchetypeRegistry.GetById(location.ArchetypeId)!;
        var (chunkIndex, _) = archetype.GetChunkLocation(location.GlobalIndex);
        return ref ChunkMask(archetype.GetChunk(chunkIndex), archetype.Layout);
    }

    /// <summary>Recomputes the chunk tag mask by OR-ing all entity tag masks in the chunk.</summary>
    /// <param name="chunkHandle">The chunk handle.</param>
    /// <param name="archetype">The archetype containing the chunk.</param>
    /// <param name="chunkIndex">The chunk index within the archetype.</param>
    private void RecomputeChunkMask(ChunkHandle chunkHandle, Archetype<TMask, TConfig> archetype, int chunkIndex)
    {
        ChunkMask(chunkHandle, archetype.Layout) = ComputeActualChunkMask(archetype, chunkIndex);
    }

    /// <summary>Computes the actual tag mask for a chunk by OR-ing all entity tag masks.</summary>
    /// <param name="archetype">The archetype containing the chunk.</param>
    /// <param name="chunkIndex">The chunk index within the archetype.</param>
    /// <returns>The computed tag mask representing the union of all entity tags in the chunk.</returns>
    private TTagMask ComputeActualChunkMask(Archetype<TMask, TConfig> archetype, int chunkIndex)
    {
        var mask = default(TTagMask);

        int entitiesPerChunk = archetype.Layout.EntitiesPerChunk;
        int entityCountInChunk = Math.Min(entitiesPerChunk, archetype.EntityCount - chunkIndex * entitiesPerChunk);

        if (entityCountInChunk <= 0)
            return mask;

        // Get chunk data and compute union of all entity tag masks
        var chunkHandle = archetype.GetChunk(chunkIndex);
        var bytes = _world.ChunkManager.GetBytes(chunkHandle);
        int baseOffset = archetype.Layout.GetBaseOffset(TEntityTags.TypeId);
        int entityTagsSize = _world.TypeInfos[TEntityTags.TypeId.Value].Size;

        for (int i = 0; i < entityCountInChunk; i++)
        {
            ref var entityTags = ref bytes.GetRef<TEntityTags>(baseOffset + i * entityTagsSize);
            mask = mask.Or(entityTags.Mask);
        }

        return mask;
    }
}
