using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Paradise.ECS;

/// <summary>
/// Diagnostic information about stale bits in chunk tag masks.
/// </summary>
/// <remarks>
/// <para>
/// Stale bits occur when tags are removed from entities but the chunk mask retains the bit
/// (sticky mask optimization). This optimization avoids expensive O(n) scans on every tag
/// removal, but can accumulate false-positive bits over time.
/// </para>
/// <para>
/// <b>Query Performance Impact:</b> Each stale bit causes tag queries to potentially check
/// chunks that no longer contain matching entities. For example, if a chunk mask has 3 stale
/// bits for tag A, B, C but no entities actually have those tags, queries for A, B, or C will
/// still examine this chunk before filtering at the entity level.
/// </para>
/// </remarks>
/// <param name="TotalChunks">Total number of chunks analyzed.</param>
/// <param name="ChunksWithStaleBits">Number of chunks that have at least one stale bit.</param>
/// <param name="TotalStaleBits">Total count of stale bits across all chunks.</param>
/// <param name="TotalActualBits">Total count of actual (non-stale) tag bits across all chunks.</param>
public readonly record struct StaleBitStatistics(
    int TotalChunks,
    int ChunksWithStaleBits,
    int TotalStaleBits,
    int TotalActualBits)
{
    /// <summary>
    /// Gets the ratio of stale bits to total bits (stale + actual).
    /// Returns 0 if there are no bits at all.
    /// </summary>
    /// <remarks>
    /// A ratio above 0.5 indicates that more than half the chunk mask bits are stale,
    /// which may warrant calling <c>RebuildChunkMasks()</c>.
    /// </remarks>
    public double StaleBitRatio => TotalStaleBits + TotalActualBits == 0
        ? 0
        : (double)TotalStaleBits / (TotalStaleBits + TotalActualBits);

    /// <summary>
    /// Gets the ratio of chunks with stale bits to total chunks.
    /// Returns 0 if there are no chunks.
    /// </summary>
    public double ChunksWithStaleBitsRatio => TotalChunks == 0
        ? 0
        : (double)ChunksWithStaleBits / TotalChunks;

    /// <summary>
    /// Gets whether the stale bit accumulation suggests rebuilding chunk masks.
    /// Returns true when <see cref="StaleBitRatio"/> exceeds 0.5 or more than 25% of chunks have stale bits.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>When to Rebuild:</b> Consider calling <c>RebuildChunkMasks()</c> when:
    /// <list type="bullet">
    /// <item><description><see cref="StaleBitRatio"/> exceeds 0.5 (50% of bits are stale)</description></item>
    /// <item><description><see cref="ChunksWithStaleBits"/> is significant relative to total chunks</description></item>
    /// <item><description>Tag query performance degrades noticeably</description></item>
    /// </list>
    /// </para>
    /// </remarks>
    public bool SuggestsRebuild => StaleBitRatio > 0.5 || ChunksWithStaleBitsRatio > 0.25;
}

/// <summary>
/// A world wrapper that provides tag support for entities.
/// Tags are stored as a component (EntityTags) that is automatically added to spawned entities.
/// </summary>
/// <typeparam name="TMask">The component mask type implementing IBitSet.</typeparam>
/// <typeparam name="TConfig">The world configuration type.</typeparam>
/// <typeparam name="TEntityTags">The EntityTags component type (generated by TagGenerator).</typeparam>
/// <typeparam name="TTagMask">The tag mask type (generated by TagGenerator as TagMask alias).</typeparam>
/// <remarks>
/// TaggedWorld wraps a standard World and adds tag-specific APIs.
/// Tags are stored in a per-entity bitmask component, enabling O(1) tag operations
/// without archetype changes.
/// </remarks>
public sealed class TaggedWorld<TMask, TConfig, TEntityTags, TTagMask> : IWorld<TMask, TConfig>, ICommandExtensionSink
    where TMask : unmanaged, IBitSet<TMask>
    where TConfig : IConfig, new()
    where TEntityTags : unmanaged, IComponent, IEntityTags<TTagMask>
    where TTagMask : unmanaged, IBitSet<TTagMask>
{
    private readonly World<TMask, TConfig> _world;

    /// <summary>
    /// Creates a new TaggedWorld with externally provided subsystems.
    /// The caller is responsible for disposing the provided resources.
    /// </summary>
    /// <param name="config">The configuration instance with runtime settings.</param>
    /// <param name="chunkManager">The chunk manager for memory allocation.</param>
    /// <param name="sharedMetadata">The shared archetype metadata.</param>
    /// <remarks>
    /// Per-chunk tag masks are not passed in and not owned: they live in a slot reserved at the end
    /// of every chunk whose archetype carries <typeparamref name="TEntityTags"/>, which the layout
    /// reserves automatically. That is what makes them travel with <c>World.CopyFrom</c> and what
    /// removes the side table this used to take.
    /// </remarks>
    public TaggedWorld(
        TConfig config,
        ChunkManager chunkManager,
        SharedArchetypeMetadata<TMask, TConfig> sharedMetadata)
    {
        _world = new World<TMask, TConfig>(config, sharedMetadata, chunkManager);
    }

    /// <summary>
    /// Gets the underlying World instance.
    /// </summary>
    public World<TMask, TConfig> World => _world;

    public IEntityManager EntityManager => _world.EntityManager;

    /// <summary>
    /// Gets the archetype registry for this world.
    /// </summary>
    public ArchetypeRegistry<TMask, TConfig> ArchetypeRegistry => _world.ArchetypeRegistry;

    /// <summary>
    /// Gets the chunk manager for memory allocation and chunk access.
    /// </summary>
    public ChunkManager ChunkManager => _world.ChunkManager;

    /// <inheritdoc/>
    public WorldEventStore Events => _world.Events;

    /// <inheritdoc/>
    public EntityIdAllocator EntityIdAllocator => _world.EntityIdAllocator;

    /// <summary>
    /// Gets the current number of live entities.
    /// </summary>
    public int EntityCount => _world.EntityCount;

    /// <summary>
    /// Spawns a new entity with the EntityTags component automatically added.
    /// </summary>
    /// <returns>The newly created entity.</returns>
    public Entity Spawn()
    {
        var entity = _world.Spawn();
        _world.AddComponent<TEntityTags>(entity);
        return entity;
    }

    /// <summary>
    /// Despawns an entity, removing it from the world.
    /// </summary>
    /// <param name="entity">The entity to despawn.</param>
    /// <returns>True if the entity was despawned; false if it was already dead.</returns>
    /// <remarks>
    /// The chunk tag mask is not recomputed immediately (sticky mask optimization).
    /// Call <see cref="RebuildChunkMasks"/> to clean up stale bits if needed.
    /// </remarks>
    public bool Despawn(Entity entity)
    {
        if (!_world.IsAlive(entity))
            return false;

        CoverSwapVictim(entity);
        _world.Despawn(entity);
        return true;
    }

    /// <summary>
    /// Cover, in advance, the tags of whichever entity a despawn is about to drag into this one's
    /// slot.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Despawn is a swap-remove: the archetype's LAST entity is moved into the hole. When the hole
    /// is in an earlier chunk that entity crosses chunks, carrying tags the destination has never
    /// seen — and unlike every other move, the entity that moves is not the one the caller named,
    /// so there is nothing to call <see cref="CoverTags"/> on afterwards. Which entity it will be
    /// is the world's business, not this wrapper's.
    /// </para>
    /// <para>
    /// So this covers the whole SOURCE CHUNK's mask instead of one entity's tags — a superset of
    /// whatever moves, which is exactly what a conservative mask is allowed to be. It costs the
    /// destination chunk some bits it may not strictly need (a scan, never a wrong answer) and it
    /// needs no cooperation from the layer below. Done BEFORE the despawn, while both chunks are
    /// still where they are.
    /// </para>
    /// <para>
    /// Nothing to do when the victim is already in the same chunk — the common case, and the reason
    /// a single-chunk archetype hides this defect completely.
    /// </para>
    /// </remarks>
    private void CoverSwapVictim(Entity entity)
    {
        var location = _world.GetLocation(entity);
        var archetype = _world.ArchetypeRegistry.GetById(location.ArchetypeId);
        if (archetype is null || !archetype.Layout.ComponentMask.Get(TEntityTags.TypeId.Value))
            return;

        var (chunkIndex, _) = archetype.GetChunkLocation(location.GlobalIndex);
        int lastChunkIndex = archetype.ChunkCount - 1;
        if (lastChunkIndex <= chunkIndex)
            return;

        var sourceMask = ChunkMask(archetype.GetChunk(lastChunkIndex), archetype.Layout);
        ref var destinationMask = ref ChunkMask(archetype.GetChunk(chunkIndex), archetype.Layout);
        destinationMask = destinationMask.Or(sourceMask);
    }

    /// <inheritdoc/>
    public void SetSystemRunInProgress(bool running) => _world.SetSystemRunInProgress(running);

    /// <summary>
    /// Clears all entities from the world.
    /// Also clears all chunk tag masks.
    /// </summary>
    public void Clear()
    {
        _world.Clear();
    }

    /// <summary>
    /// Computes statistics about stale bits in chunk tag masks.
    /// Use this to monitor whether <see cref="RebuildChunkMasks"/> should be called.
    /// </summary>
    /// <returns>A <see cref="StaleBitStatistics"/> containing diagnostic information.</returns>
    /// <remarks>
    /// <para>
    /// Stale bits occur when tags are removed from entities but the chunk mask retains the bit
    /// (sticky mask optimization). While this doesn't affect correctness, it can degrade query
    /// performance by causing false-positive chunk matches.
    /// </para>
    /// <para>
    /// This operation is O(n) where n is the total number of entities. Use sparingly in
    /// performance-critical code paths.
    /// </para>
    /// </remarks>
    public StaleBitStatistics ComputeStaleBitStatistics()
    {
        int totalChunks = 0;
        int totalStaleBits = 0;
        int totalActualBits = 0;
        int chunksWithStaleBits = 0;

        for (int index = 0; index < _world.Archetypes.Count; index++)
        {
            Archetype<TMask, TConfig>? archetype = _world.Archetypes[index];
            if (archetype is null || !archetype.Layout.ComponentMask.Get(TEntityTags.TypeId.Value))
                continue;

            int chunkCount = archetype.ChunkCount;
            for (int chunkIndex = 0; chunkIndex < chunkCount; chunkIndex++)
            {
                var currentMask = ChunkMask(archetype.GetChunk(chunkIndex), archetype.Layout);
                var actualMask = ComputeActualChunkMask(archetype, chunkIndex);

                int currentBits = currentMask.PopCount();
                int actualBits = actualMask.PopCount();
                int staleBits = currentBits - actualBits;

                totalChunks++;
                totalStaleBits += staleBits;
                totalActualBits += actualBits;
                if (staleBits > 0)
                    chunksWithStaleBits++;
            }
        }

        return new StaleBitStatistics(totalChunks, chunksWithStaleBits, totalStaleBits, totalActualBits);
    }

    /// <summary>
    /// Rebuilds all chunk tag masks by scanning all entities.
    /// Call this to clean up stale bits after tag removals or despawns.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This operation is O(n) where n is the total number of entities.
    /// Best called at natural breakpoints (level transitions, loading screens).
    /// </para>
    /// <para>
    /// <b>Performance Impact of Stale Bits:</b> Stale bits cause tag queries to check chunks
    /// that no longer contain matching entities. For workloads with frequent tag removals,
    /// consider calling this method periodically or when <see cref="ComputeStaleBitStatistics"/>
    /// shows high stale bit counts.
    /// </para>
    /// </remarks>
    public void RebuildChunkMasks()
    {
        // No global clear: every slot lives in the chunk it describes and is overwritten below, so
        // there is nothing to reset first — and nothing belonging to another world to destroy. That
        // hazard was real while the masks lived in a registry shared across worlds.
        // Iterate all archetypes that have EntityTags component
        for (int index = 0; index < _world.Archetypes.Count; index++)
        {
            Archetype<TMask, TConfig>? archetype = _world.Archetypes[index];
            if (archetype is null || !archetype.Layout.ComponentMask.Get(TEntityTags.TypeId.Value))
                continue;

            int chunkCount = archetype.ChunkCount;
            for (int chunkIndex = 0; chunkIndex < chunkCount; chunkIndex++)
            {
                var chunkHandle = archetype.GetChunk(chunkIndex);
                RecomputeChunkMask(chunkHandle, archetype, chunkIndex);
            }
        }
    }

    /// <summary>
    /// Checks if an entity is still alive.
    /// </summary>
    /// <param name="entity">The entity to check.</param>
    /// <returns>True if the entity is alive.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool IsAlive(Entity entity) => _world.IsAlive(entity);

    /// <summary>
    /// Adds a tag to an entity.
    /// </summary>
    /// <typeparam name="TTag">The tag type to add.</typeparam>
    /// <param name="entity">The entity to add the tag to.</param>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void AddTag<TTag>(Entity entity) where TTag : ITag
        => AddTag(entity, TTag.TagId.Value);

    private void AddTag(Entity entity, int tagId)
    {
        _world.AssertStructuralChangesAllowed(nameof(AddTag));
        ref var tags = ref _world.GetComponent<TEntityTags>(entity);
        tags.Mask = tags.Mask.Set(tagId);
        ref var chunkMask = ref ChunkMaskOf(entity);
        chunkMask = chunkMask.Or(default(TTagMask).Set(tagId));
    }

    /// <summary>
    /// Removes a tag from an entity.
    /// </summary>
    /// <typeparam name="TTag">The tag type to remove.</typeparam>
    /// <param name="entity">The entity to remove the tag from.</param>
    /// <remarks>
    /// The chunk tag mask is not recomputed immediately (sticky mask optimization).
    /// This may result in false positives during tag queries, which is safe but may
    /// cause queries to check a few extra entities. Call <see cref="RebuildChunkMasks"/>
    /// to clean up stale bits if needed.
    /// </remarks>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void RemoveTag<TTag>(Entity entity) where TTag : ITag
        => RemoveTag(entity, TTag.TagId.Value);

    private void RemoveTag(Entity entity, int tagId)
    {
        _world.AssertStructuralChangesAllowed(nameof(RemoveTag));
        ref var tags = ref _world.GetComponent<TEntityTags>(entity);
        tags.Mask = tags.Mask.Clear(tagId);
        // Chunk mask not recomputed (sticky mask) - may have stale bits
    }

    /// <inheritdoc/>
    public void PlayExtension(Type opType, Entity entity, ReadOnlySpan<byte> data)
    {
        if (opType == typeof(AddTagOp))
        {
            AddTag(entity, ReadTagId(data));
            return;
        }

        if (opType == typeof(RemoveTagOp))
        {
            RemoveTag(entity, ReadTagId(data));
            return;
        }

        throw new InvalidOperationException($"Unknown command extension '{opType}'.");
    }

    private static int ReadTagId(ReadOnlySpan<byte> data)
    {
        if (data.Length != sizeof(int))
        {
            throw new InvalidOperationException("Tag command payload must be a 4-byte tag id.");
        }

        return MemoryMarshal.Read<int>(data);
    }

    /// <summary>
    /// Replaces this world's contents with a copy of <paramref name="source"/>, tags included.
    /// </summary>
    /// <param name="source">The world to copy from. Must share this world's SharedArchetypeMetadata.</param>
    /// <remarks>
    /// <para>
    /// The tagged counterpart of <see cref="World{TMask,TConfig}.CopyFrom"/>, and the reason a
    /// tagged world can take part in snapshot execution at all: a host that publishes each step by
    /// copying the stepped world into a pooled twin needs this, and without it referencing
    /// Paradise.ECS.Tag cost a consumer its snapshot loop.
    /// </para>
    /// <para>
    /// <b>Per-entity tags need no special handling.</b> They live in the <c>EntityTags</c>
    /// COMPONENT, which sits in the chunks that <see cref="World{TMask,TConfig}.CopyFrom"/> copies,
    /// so every entity arrives already carrying its mask.
    /// </para>
    /// <para>
    /// <b>Chunk masks do.</b> the per-chunk mask table was keyed by
    /// <c>ChunkHandle.Id</c>, and the copy puts the data in DIFFERENT chunks — so this world's new
    /// chunks arrive with no entries at all. Leaving them that way would not be a slow answer but a
    /// WRONG one: <c>ChunkMayMatch</c> reads a clear bit as proof the chunk holds no such tag, so
    /// an empty mask makes a consumer skip chunks whose entities really are tagged. Whatever this
    /// method does, it cannot do nothing.
    /// </para>
    /// <para>
    /// <b>The masks are COPIED, not recomputed.</b> Source chunk j pairs with destination chunk j —
    /// the archetype ids match through the shared metadata and <c>CopyChunksFrom</c> copies in index
    /// order, which is the same pairing <see cref="SnapshotChunkPairing"/> already relies on. So the
    /// answer is already known and costs O(chunks) to move; recomputing it would re-read every
    /// entity's tag mask, O(entities), on every publish — and a host publishing a snapshot per step
    /// pays that per step.
    /// </para>
    /// <para>
    /// What copying gives up is that stale bits ride along. Masks are sticky —
    /// <see cref="RemoveTag{TTag}"/> clears the entity's bit and leaves the chunk's — so a source
    /// carrying bits no entity has any more hands them to the copy. That is deliberate: it is
    /// faithful (a copy should hold what its source holds), it is safe in the only direction that
    /// matters (an extra bit costs a scan, a missing one costs a correct answer), and recomputing
    /// here would not have fixed the real problem anyway — it would clean the SNAPSHOTS while the
    /// live world, the one systems actually query, kept accumulating. That is what
    /// <see cref="RebuildChunkMasks"/> and <see cref="StaleBitStatistics.SuggestsRebuild"/> are for.
    /// </para>
    /// <para>
    /// <b>Deliberately not <see cref="RebuildChunkMasks"/>.</b> That method CLEARS the registry
    /// first, and under <see cref="SharedTaggedWorld{TMask,TConfig,TEntityTags,TTagMask}"/> the
    /// registry is shared by every world made from one shared — so rebuilding "this world's" masks
    /// that way would erase its siblings' and rebuild only its own. Publishing a snapshot would then
    /// blank the live world's masks on every step. This writes only this world's entries.
    /// </para>
    /// </remarks>
    /// <exception cref="InvalidOperationException">Copying a world to itself, or between worlds
    /// that do not share metadata (both surfaced by the inner world).</exception>
    public void CopyFrom(TaggedWorld<TMask, TConfig, TEntityTags, TTagMask> source)
    {
        ArgumentNullException.ThrowIfNull(source);

        _world.CopyFrom(source._world);
    }

    /// <summary>
    /// Checks if an entity has a specific tag.
    /// </summary>
    /// <typeparam name="TTag">The tag type to check.</typeparam>
    /// <param name="entity">The entity to check.</param>
    /// <returns>True if the entity has the tag.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool HasTag<TTag>(Entity entity) where TTag : ITag
    {
        ref var tags = ref _world.GetComponent<TEntityTags>(entity);
        return tags.Mask.Get(TTag.TagId);
    }

    /// <summary>
    /// The tag mask of the CHUNK <paramref name="entity"/> lives in: the union of the tags of every
    /// entity in it.
    /// </summary>
    /// <remarks>
    /// A conservative summary, not an exact one. Bits are OR-ed in when a tag is added and left
    /// alone when one is removed (see <see cref="RemoveTag{TTag}"/>), so a set bit means "some
    /// entity here may carry this" and only a clear bit is proof of absence. That asymmetry is what
    /// makes it safe to skip a chunk on a clear bit and never safe to trust a set one.
    /// </remarks>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public TTagMask GetChunkMask(Entity entity) => ChunkMaskOf(entity);

    /// <summary>
    /// Gets the full tag mask for an entity.
    /// </summary>
    /// <param name="entity">The entity to get tags from.</param>
    /// <returns>The tag mask.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public TTagMask GetTags(Entity entity)
    {
        return _world.GetComponent<TEntityTags>(entity).Mask;
    }

    /// <summary>
    /// Sets the full tag mask for an entity.
    /// </summary>
    /// <param name="entity">The entity to set tags on.</param>
    /// <param name="tags">The tag mask to set.</param>
    /// <remarks>
    /// When tags are removed, the chunk tag mask is not recomputed (sticky mask optimization).
    /// Call <see cref="RebuildChunkMasks"/> to clean up stale bits if needed.
    /// </remarks>
    public void SetTags(Entity entity, TTagMask tags)
    {
        ref var entityTags = ref _world.GetComponent<TEntityTags>(entity);
        var oldMask = entityTags.Mask;
        entityTags.Mask = tags;

        // Only update chunk mask for added tags (sticky mask optimization)
        var addedTags = tags.AndNot(oldMask); // tags in new but not in old

        if (!addedTags.Equals(default(TTagMask)))
        {
            ref var chunkMask = ref ChunkMaskOf(entity);
            chunkMask = chunkMask.Or(addedTags);
        }
        // Removed tags: chunk mask not recomputed (sticky) - may have stale bits
    }

    /// <summary>
    /// Gets a reference to a component on an entity.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public ref T GetComponent<T>(Entity entity) where T : unmanaged, IComponent
        => ref _world.GetComponent<T>(entity);

    /// <inheritdoc/>
    public bool TryGetComponent<T>(Entity entity, out T value) where T : unmanaged, IComponent
        => _world.TryGetComponent(entity, out value);

    /// <inheritdoc/>
    public bool TrySetComponent<T>(Entity entity, T value) where T : unmanaged, IComponent
        => _world.TrySetComponent(entity, value);

    /// <summary>
    /// Checks if an entity has a component.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool HasComponent<T>(Entity entity) where T : unmanaged, IComponent
        => _world.HasComponent<T>(entity);

    /// <summary>
    /// Adds a component to an entity.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void AddComponent<T>(Entity entity, T value = default) where T : unmanaged, IComponent
    {
        // Changes archetype, so the entity moves to a chunk that knows nothing of its tags.
        _world.AddComponent(entity, value);
        CoverTags(entity);
    }

    /// <summary>
    /// Removes a component from an entity.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void RemoveComponent<T>(Entity entity) where T : unmanaged, IComponent
    {
        _world.RemoveComponent<T>(entity);
        CoverTags(entity);
    }

    /// <inheritdoc/>
    public void AddComponentRaw(Entity entity, ComponentId componentId, ReadOnlySpan<byte> data)
    {
        _world.AddComponentRaw(entity, componentId, data);
        CoverTags(entity);
    }

    /// <inheritdoc/>
    public void RemoveComponentRaw(Entity entity, ComponentId componentId)
    {
        _world.RemoveComponentRaw(entity, componentId);
        CoverTags(entity);
    }

    /// <inheritdoc/>
    public void SetComponentRaw(Entity entity, ComponentId componentId, ReadOnlySpan<byte> data)
        => _world.SetComponentRaw(entity, componentId, data);

    /// <inheritdoc/>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public Entity CreateEntity<TBuilder>(TBuilder builder) where TBuilder : unmanaged, IComponentsBuilder
    {
        var wrappedBuilder = new EnsureComponent<TEntityTags, TBuilder> { InnerBuilder = builder };
        var entity = _world.CreateEntity(wrappedBuilder);
        // A builder can carry tags (AddTag composes onto it), so a brand-new entity may already be
        // tagged before its chunk has been told.
        CoverTags(entity);
        return entity;
    }

    /// <inheritdoc/>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public Entity CreateEntity(in TMask mask)
    {
        // The tag storage is added to the mask exactly as the builder overload wraps its builder in
        // EnsureComponent<TEntityTags>: a tag can only be applied to an entity whose archetype
        // already reserves the bits, and a caller assembling a mask at runtime has no more business
        // remembering that than one spelling a builder does.
        var entity = _world.CreateEntity(mask.Set(TEntityTags.TypeId));
        // No builder means no tag can arrive pre-set, so this cannot find anything to cover today.
        // Kept for the same reason the builder path has it: what may seed a tag is the caller's
        // business, and a new entity that is already tagged must reach its chunk mask.
        CoverTags(entity);
        return entity;
    }

    /// <inheritdoc/>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public Entity OverwriteEntity<TBuilder>(Entity entity, TBuilder builder) where TBuilder : unmanaged, IComponentsBuilder
    {
        var wrappedBuilder = new EnsureComponent<TEntityTags, TBuilder> { InnerBuilder = builder };
        var result = _world.OverwriteEntity(entity, wrappedBuilder);
        CoverTags(result);
        return result;
    }

    /// <inheritdoc/>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public Entity AddComponents<TBuilder>(Entity entity, TBuilder builder) where TBuilder : unmanaged, IComponentsBuilder
    {
        var result = _world.AddComponents(entity, builder);
        CoverTags(result);
        return result;
    }

    /// <summary>
    /// Make this entity's chunk admit to the tags the entity carries.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Called after anything that can move an entity between chunks. The entity's tags travel with
    /// it — they live in its <typeparamref name="TEntityTags"/> component — but the chunk it lands
    /// in has never heard of them, and a chunk mask that is missing bits is the one kind of wrong
    /// that costs correctness: a consumer skipping a chunk on a clear bit steps straight over
    /// entities that do carry the tag.
    /// </para>
    /// <para>
    /// Only ever ORs, which is what makes it cheap to call defensively: the mask is a conservative
    /// superset by design, so adding bits can never make an answer wrong, only make a scan longer.
    /// </para>
    /// </remarks>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void CoverTags(Entity entity)
    {
        if (!_world.HasComponent<TEntityTags>(entity))
            return;

        var tags = _world.GetComponent<TEntityTags>(entity).Mask;
        if (tags.Equals(default(TTagMask)))
            return;

        ref var chunkMask = ref ChunkMaskOf(entity);
        chunkMask = chunkMask.Or(tags);
    }

    /// <summary>
    /// The chunk's tag mask: the union of the tag masks of the entities it holds, living in the
    /// slot the layout reserved at the end of the chunk.
    /// </summary>
    /// <remarks>
    /// A <c>ref</c> into chunk memory rather than a lookup, so OR-ing a bit in is a read-modify-
    /// write on the bytes themselves. It also means the value is carried by any operation that
    /// copies chunks — which is the whole reason it lives here rather than in a table beside the
    /// world.
    /// </remarks>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private ref TTagMask ChunkMask(
        ChunkHandle chunk, scoped in ImmutableArchetypeLayout<TMask, TConfig> layout)
    {
        int offset = layout.GetChunkAggregateOffset(TEntityTags.TypeId, _world.TypeInfos);
        return ref _world.ChunkManager.GetBytes(chunk).GetRef<TTagMask>(offset);
    }

    /// <summary>The chunk mask of the chunk <paramref name="entity"/> lives in.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private ref TTagMask ChunkMaskOf(Entity entity)
    {
        var location = _world.GetLocation(entity);
        var archetype = _world.ArchetypeRegistry.GetById(location.ArchetypeId)!;
        var (chunkIndex, _) = archetype.GetChunkLocation(location.GlobalIndex);
        return ref ChunkMask(archetype.GetChunk(chunkIndex), archetype.Layout);
    }

    /// <summary>
    /// Recomputes the chunk tag mask by OR-ing all entity tag masks in the chunk.
    /// </summary>
    /// <param name="chunkHandle">The chunk handle.</param>
    /// <param name="archetype">The archetype containing the chunk.</param>
    /// <param name="chunkIndex">The chunk index within the archetype.</param>
    private void RecomputeChunkMask(ChunkHandle chunkHandle, Archetype<TMask, TConfig> archetype, int chunkIndex)
    {
        ChunkMask(chunkHandle, archetype.Layout) = ComputeActualChunkMask(archetype, chunkIndex);
    }

    /// <summary>
    /// Computes the actual tag mask for a chunk by OR-ing all entity tag masks.
    /// </summary>
    /// <param name="archetype">The archetype containing the chunk.</param>
    /// <param name="chunkIndex">The chunk index within the archetype.</param>
    /// <returns>The computed tag mask representing the union of all entity tags in the chunk.</returns>
    private TTagMask ComputeActualChunkMask(Archetype<TMask, TConfig> archetype, int chunkIndex)
    {
        var mask = default(TTagMask);

        // Calculate how many entities are in this specific chunk
        int entitiesPerChunk = archetype.Layout.EntitiesPerChunk;
        int totalEntities = archetype.EntityCount;
        int entityCountInChunk;

        if ((chunkIndex + 1) * entitiesPerChunk <= totalEntities)
        {
            // Full chunk
            entityCountInChunk = entitiesPerChunk;
        }
        else
        {
            // Last chunk (partially filled)
            entityCountInChunk = totalEntities - chunkIndex * entitiesPerChunk;
        }

        if (entityCountInChunk <= 0)
            return mask;

        // Get chunk data and compute union of all entity tag masks
        var chunkHandle = archetype.GetChunk(chunkIndex);
        var bytes = _world.ChunkManager.GetBytes(chunkHandle);
        int baseOffset = archetype.Layout.GetBaseOffset(TEntityTags.TypeId);
        int entityTagsSize = _world.TypeInfos[TEntityTags.TypeId.Value].Size;

        for (int i = 0; i < entityCountInChunk; i++)
        {
            ref var entityTags = ref bytes.GetRef<TEntityTags>(baseOffset + i * entityTagsSize);
            mask = mask.Or(entityTags.Mask);
        }

        return mask;
    }
}
