<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\Paradise.ECS.Common.props" />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <NoWarn>$(NoWarn);CA1707;CA1515;PECS016</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TUnit" />
    <ProjectReference Include="..\Paradise.ECS.Managed\Paradise.ECS.Managed.csproj" />
    <ProjectReference Include="..\Paradise.ECS.Tag\Paradise.ECS.Tag.csproj" />
    <ProjectReference Include="..\Paradise.ECS.Generators\Paradise.ECS.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <Using Include="Paradise.ECS" />
  </ItemGroup>
</Project>
