<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Paradise.Ui.Noesis.Host.Test</AssemblyName>
    <RootNamespace>Paradise.Ui.Noesis.Host.Test</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
    <PackageReference Include="WebGPUSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Paradise.Ui.Noesis.Host\Paradise.Ui.Noesis.Host.csproj" />
  </ItemGroup>
</Project>
