using System.Text.Json.Nodes;

using Paradise.Assets.Project;

namespace Paradise.Assets.Pipeline;

/// <summary>
/// What a texture is encoded AS. Every preset is UASTC (high quality, near-lossless) rather
/// than ETC1S/basis-lz: ETC1S is ~2 bpp and visibly degrades detailed or saturated colour maps
/// (it lifts dark, saturated texels), which diverged the .NET runtime's albedo from Godot's,
/// where the source PNG is imported at full quality. UASTC transcodes to the BC7 the engine
/// already uses and matches Godot's fidelity, so both hosts show one image. Zstd
/// supercompression keeps the on-disk size reasonable.
/// </summary>
public enum TextureEncodingPreset
{
    /// <summary>Base colour, emissive.</summary>
    UastcColorSrgb,

    /// <summary>Linear colour: masks, height, displacement.</summary>
    UastcColorLinear,

    /// <summary>Packed data: metallic, roughness, occlusion.</summary>
    UastcDataLinear,

    UastcNormalLinear,
}

/// <summary>The encode decisions: which <c>ktx create</c> argv a preset means, and which preset an image gets from its material slot or its name.</summary>
/// <remarks>
/// Pure functions over strings and glTF JSON; no tool, no filesystem. The one accepted
/// inaccuracy: mipmaps are generated by <c>ktx</c> from texels the container declares linear,
/// so colour textures have their mips filtered in gamma space — slightly dark at distance. The
/// alternative (tag sRGB, filter linear) triggers Godot's double decode described in
/// <see cref="CreateArguments"/>; the wrong-at-distance mip is the smaller wrong.
/// </remarks>
public static class TextureEncodePolicy
{
    /// <summary>
    /// v5 differences from the removed <c>toktx</c>: KTX2 output is implicit (no <c>--t2</c>),
    /// top-left origin is the default, <c>--format</c> is mandatory, the transfer function rides
    /// on the format (+ <c>--assign-tf</c> for the input), ETC1S is spelled <c>basis-lz</c>,
    /// Zstandard is <c>--zstd</c>, and the positional order is INPUT then OUTPUT.
    /// <see cref="TextureQuality.Fast"/> drops UASTC quality to 0: the
    /// <c>texture_quality = "fast"</c> iteration setting, never for shipping.
    /// </summary>
    public static string CreateArguments(TextureEncodingPreset preset, string outputPath, string sourcePath, TextureQuality quality)
    {
        ArgumentNullException.ThrowIfNull(outputPath);
        ArgumentNullException.ThrowIfNull(sourcePath);

        var arguments = new List<string> { "create", "--generate-mipmap", "--format", "R8G8B8A8_UNORM", "--assign-tf", "linear" };

        // Colour texels ARE sRGB-encoded, but the container is deliberately tagged LINEAR:
        // Godot 4.7 double-decodes glTF KHR_texture_basisu KTX2s whose DFD says sRGB (one decode
        // at import + one via the sRGB VRAM format), rendering colour textures visibly darker
        // than authored (gray 188 read back as 128). A linear-tagged container makes Godot decode
        // exactly once, and the .NET runtime picks its GPU format by USAGE (ColorSrgb → BC7-sRGB),
        // ignoring the DFD — so both hosts show the authored colours. Revisit if Godot fixes the
        // double decode.
        if (preset == TextureEncodingPreset.UastcNormalLinear) arguments.Add("--normal-mode");

        arguments.AddRange(["--encode", "uastc", "--uastc-quality", quality == TextureQuality.Fast ? "0" : "2", "--zstd", "10"]);
        arguments.Add(ProcessTools.QuoteArgument(sourcePath));
        arguments.Add(ProcessTools.QuoteArgument(outputPath));
        return string.Join(" ", arguments);
    }

    /// <summary>The preset each image gets from the material slots that bind it; an image bound to nothing is absent, and the caller falls back to its name.</summary>
    public static Dictionary<int, TextureEncodingPreset> MaterialPresets(JsonObject gltf)
    {
        ArgumentNullException.ThrowIfNull(gltf);

        var presets = new Dictionary<int, TextureEncodingPreset>();
        if (gltf["materials"] is not JsonArray materials
            || gltf["textures"] is not JsonArray textures
            || gltf["images"] is not JsonArray images)
        {
            return presets;
        }

        foreach (var material in materials.OfType<JsonObject>())
        {
            var pbr = material["pbrMetallicRoughness"] as JsonObject;
            Bind(pbr?["baseColorTexture"], TextureEncodingPreset.UastcColorSrgb);
            Bind(material["emissiveTexture"], TextureEncodingPreset.UastcColorSrgb);
            Bind(pbr?["metallicRoughnessTexture"], TextureEncodingPreset.UastcDataLinear);
            Bind(material["normalTexture"], TextureEncodingPreset.UastcNormalLinear);
            Bind(material["occlusionTexture"], TextureEncodingPreset.UastcDataLinear);
        }

        return presets;

        void Bind(JsonNode? textureInfo, TextureEncodingPreset preset)
        {
            var textureIndex = textureInfo?["index"]?.GetValue<int>();
            if (textureIndex is not { } t || t < 0 || t >= textures.Count || textures[t] is not JsonObject texture) return;

            var imageIndex = texture["source"]?.GetValue<int>();
            if (imageIndex is not { } i || i < 0 || i >= images.Count) return;

            presets[i] = presets.TryGetValue(i, out var existing) ? Merge(existing, preset) : preset;
        }
    }

    /// <summary>One image bound to two slots keeps the more specific preset: normal over data over linear colour over sRGB.</summary>
    internal static TextureEncodingPreset Merge(TextureEncodingPreset existing, TextureEncodingPreset next)
    {
        if (existing == TextureEncodingPreset.UastcNormalLinear || next == TextureEncodingPreset.UastcNormalLinear) return TextureEncodingPreset.UastcNormalLinear;
        if (existing == TextureEncodingPreset.UastcDataLinear || next == TextureEncodingPreset.UastcDataLinear) return TextureEncodingPreset.UastcDataLinear;
        if (existing == TextureEncodingPreset.UastcColorLinear || next == TextureEncodingPreset.UastcColorLinear) return TextureEncodingPreset.UastcColorLinear;
        return TextureEncodingPreset.UastcColorSrgb;
    }

    public static TextureEncodingPreset PresetFromImageName(JsonObject image)
    {
        ArgumentNullException.ThrowIfNull(image);
        return PresetFromImageName(image["name"]?.GetValue<string>() ?? "");
    }

    /// <summary>
    /// Matches whole name tokens only: a substring rule made <c>Damask</c> a mask and
    /// <c>Chaos_Albedo</c> an AO map, encoding colour as linear data with no error.
    /// </summary>
    public static TextureEncodingPreset PresetFromImageName(string imageName)
    {
        ArgumentNullException.ThrowIfNull(imageName);

        var tokens = new HashSet<string>(NameTokens(imageName), StringComparer.OrdinalIgnoreCase);
        if (tokens.Overlaps(["Normal", "NormalMap", "Bump"])) return TextureEncodingPreset.UastcNormalLinear;
        if (tokens.Overlaps(["Metallic", "Metalness", "Roughness", "Gloss", "Occlusion", "AO"])) return TextureEncodingPreset.UastcDataLinear;
        if (tokens.Overlaps(["Mask", "Height", "Displacement"])) return TextureEncodingPreset.UastcColorLinear;
        return TextureEncodingPreset.UastcColorSrgb;
    }

    /// <summary>Splits on separators and on lower→upper case boundaries: <c>Wall_NormalMap</c> → Wall, NormalMap, Normal, Map.</summary>
    internal static IEnumerable<string> NameTokens(string imageName)
    {
        foreach (var segment in imageName.Split(['_', '-', ' ', '.', '/'], StringSplitOptions.RemoveEmptyEntries))
        {
            yield return segment;

            var start = 0;
            for (var i = 1; i < segment.Length; i++)
            {
                var boundary = char.IsUpper(segment[i]) && !char.IsUpper(segment[i - 1])
                    || char.IsDigit(segment[i]) != char.IsDigit(segment[i - 1]);
                if (!boundary) continue;

                if (i > start) yield return segment.Substring(start, i - start);
                start = i;
            }

            if (start > 0 && start < segment.Length) yield return segment.Substring(start);
        }
    }
}
