using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using WebGpuSharp;

namespace Paradise.Ui.Noesis;

/// <summary>Pure managed Noesis RenderDevice on WebGPU. Feature surface: the full paint ×
/// effect shader matrix (WGSL generated by <see cref="NoesisShaderCatalog"/> from the ported
/// reference templates), stencil masking (Mask/Clear + Equal_* modes on an always-attached
/// Stencil8 target), Noesis blend modes, per-batch sampler states, offscreen render targets
/// for opacity groups and effects (Blur/Shadow gaussian passes), and sub-allocated dynamic
/// vertex/index/uniform buffers (safe under WebGPU's ordered-queue WriteBuffer model).
///
/// Frame protocol (driven by the host): <see cref="BeginFrame"/> with the frame's command
/// encoder and color target → <c>view.Renderer.RenderOffscreen()</c> (the device opens one
/// render pass per offscreen surface) → <c>view.Renderer.Render()</c> (the onscreen pass,
/// LoadOp.Load so UI composites over the scene) → <see cref="EndFrame"/>.
///
/// Out of scope (skipped + counted, never fatal): Custom_Effect pixel shaders, dual-source
/// blending (SrcOver_Dual falls back to SrcOver), MSAA offscreen surfaces (rendered at 1x),
/// and LCD subpixel text (SDF_LCD_* runs the regular SDF shader — Caps reports
/// SubpixelRendering=false so Noesis should not request it).</summary>
public sealed class NoesisRenderDevice : global::Noesis.RenderDevice, IDisposable
{
    private const uint VertexBufferBytes = 8 * 1024 * 1024;
    private const uint IndexBufferBytes = 2 * 1024 * 1024;
    private const uint UniformRingBytes = 1024 * 1024;
    private const uint UniformAlign = 256;
    private const WebGpuSharp.TextureFormat StencilFormat = WebGpuSharp.TextureFormat.Stencil8;

    public readonly HashSet<string> Unsupported = new();

    private readonly Device _device;
    private readonly Queue _queue;
    private readonly WebGpuSharp.TextureFormat _colorFormat;

    private readonly WebGpuSharp.Buffer _vertexBuffer;
    private readonly WebGpuSharp.Buffer _indexBuffer;
    private readonly WebGpuSharp.Buffer _uniformBuffer;
    private readonly byte[] _vertexScratch = new byte[VertexBufferBytes];
    private readonly byte[] _indexScratch = new byte[IndexBufferBytes];
    private GCHandle _vertexPin;
    private GCHandle _indexPin;
    private uint _mappedVertexBytes;
    private uint _mappedIndexBytes;
    private uint _vertexCursor;
    private uint _indexCursor;
    private uint _vertexBase;
    private uint _indexBase;
    private uint _uniformCursor;
    private readonly byte[] _uniformScratch = new byte[512];

    private readonly BindGroupLayout _bindGroupLayout;
    private readonly PipelineLayout _pipelineLayout;
    private readonly Dictionary<PipelineKey, RenderPipeline> _pipelines = new();
    private readonly Dictionary<BindKey, BindGroup> _bindGroups = new();
    private readonly Sampler[] _samplers = new Sampler[64];
    private readonly NoesisTexture _dummyRgba;
    private readonly NoesisTexture _dummyR8;

    private CommandEncoder? _encoder;
    private RenderPassEncoder? _pass;
    private TextureView? _onscreenColor;
    private WebGpuSharp.Texture? _onscreenStencil;
    private TextureView? _onscreenStencilView;
    private uint _targetWidth;
    private uint _targetHeight;
    private NoesisRenderTarget? _activeSurface;
    private byte _stencilRef = byte.MaxValue; // force first SetStencilReference

    private readonly record struct PipelineKey(int Shader, global::Noesis.BlendMode Blend, global::Noesis.StencilMode Stencil, bool ColorEnable);
    private readonly record struct BindKey(uint VsSlot, uint Ps0Slot, uint Ps1Slot, int Pattern, int Ramps, int Image, int Glyphs, int Shadow, byte Sampler);

    private sealed class NoesisTexture : global::Noesis.Texture
    {
        private static int s_nextId;

        public NoesisTexture(WebGpuSharp.Texture native, TextureView view, uint width, uint height, global::Noesis.TextureFormat format, bool hasMips)
        {
            Native = native; View = view; W = width; H = height; Format = format; Mips = hasMips;
            Id = ++s_nextId;
        }

        public int Id { get; }
        public WebGpuSharp.Texture Native { get; }
        public TextureView View { get; }
        public uint W { get; }
        public uint H { get; }
        public global::Noesis.TextureFormat Format { get; }
        public bool Mips { get; }
        public override uint Width => W;
        public override uint Height => H;
        public override bool HasMipMaps => Mips;
        public override bool IsInverted => false;
        public override bool HasAlpha => Format != global::Noesis.TextureFormat.RGBX8;
    }

    private sealed class NoesisRenderTarget : global::Noesis.RenderTarget
    {
        public NoesisRenderTarget(NoesisTexture color, WebGpuSharp.Texture stencil, TextureView stencilView)
        {
            Color = color; Stencil = stencil; StencilView = stencilView;
        }

        public NoesisTexture Color { get; }
        public WebGpuSharp.Texture Stencil { get; }
        public TextureView StencilView { get; }
        public override global::Noesis.Texture Texture => Color;
    }

    public NoesisRenderDevice(Device device, WebGpuSharp.TextureFormat colorFormat)
    {
        _device = device;
        _queue = device.GetQueue() ?? throw new InvalidOperationException("Device has no queue.");
        _colorFormat = colorFormat;

        _vertexBuffer = CreateBuffer("global::Noesis.VB", VertexBufferBytes, BufferUsage.Vertex | BufferUsage.CopyDst);
        _indexBuffer = CreateBuffer("global::Noesis.IB", IndexBufferBytes, BufferUsage.Index | BufferUsage.CopyDst);
        _uniformBuffer = CreateBuffer("global::Noesis.Uniforms", UniformRingBytes, BufferUsage.Uniform | BufferUsage.CopyDst);
        _vertexPin = GCHandle.Alloc(_vertexScratch, GCHandleType.Pinned);
        _indexPin = GCHandle.Alloc(_indexScratch, GCHandleType.Pinned);

        // Superset layout shared by every pipeline; unused bindings get dummy resources.
        _bindGroupLayout = _device.CreateBindGroupLayout(new BindGroupLayoutDescriptor
        {
            Label = "global::Noesis.BindGroupLayout",
            Entries =
            [
                UniformEntry(0, ShaderStage.Vertex, 80),
                UniformEntry(1, ShaderStage.Fragment, 32),
                UniformEntry(2, ShaderStage.Fragment, 512),
                TextureEntry(3), TextureEntry(4), TextureEntry(5), TextureEntry(6), TextureEntry(7),
                new BindGroupLayoutEntry
                {
                    Binding = 8,
                    Visibility = ShaderStage.Fragment,
                    Sampler = new SamplerBindingLayout { Type = SamplerBindingType.Filtering },
                },
            ],
        }) ?? throw new InvalidOperationException("Noesis bind group layout creation failed.");
        _pipelineLayout = _device.CreatePipelineLayout(new PipelineLayoutDescriptor
        {
            BindGroupLayouts = [_bindGroupLayout],
        }) ?? throw new InvalidOperationException("Noesis pipeline layout creation failed.");

        _dummyRgba = CreateNativeTexture("global::Noesis.DummyRgba", 1, 1, 1, global::Noesis.TextureFormat.RGBA8);
        _dummyR8 = CreateNativeTexture("global::Noesis.DummyR8", 1, 1, 1, global::Noesis.TextureFormat.R8);

        static BindGroupLayoutEntry UniformEntry(uint binding, ShaderStage stage, ulong minSize) => new()
        {
            Binding = binding,
            Visibility = stage,
            Buffer = new BufferBindingLayout { Type = BufferBindingType.Uniform, HasDynamicOffset = true, MinBindingSize = minSize },
        };
        static BindGroupLayoutEntry TextureEntry(uint binding) => new()
        {
            Binding = binding,
            Visibility = ShaderStage.Fragment,
            Texture = new TextureBindingLayout { SampleType = TextureSampleType.Float, ViewDimension = TextureViewDimension.D2, Multisampled = false },
        };
    }

    private WebGpuSharp.Buffer CreateBuffer(string label, ulong size, BufferUsage usage) =>
        _device.CreateBuffer(new BufferDescriptor { Label = label, Size = size, Usage = usage, MappedAtCreation = false })
            ?? throw new InvalidOperationException($"{label}: buffer creation failed.");

    // ---- frame protocol ----

    /// <summary>Attach the device to this frame's encoder and color target. The onscreen pass
    /// loads the existing contents (UI composites over the scene) and clears the device-owned
    /// stencil. Must be called before <c>view.Renderer.RenderOffscreen()</c>.</summary>
    public void BeginFrame(CommandEncoder encoder, TextureView colorTarget, uint width, uint height)
    {
        _encoder = encoder;
        _onscreenColor = colorTarget;
        if (_onscreenStencil is null || _targetWidth != width || _targetHeight != height)
        {
            _onscreenStencil?.Destroy();
            _onscreenStencil = _device.CreateTexture(new TextureDescriptor
            {
                Label = "global::Noesis.OnscreenStencil",
                Size = new Extent3D(width, height, 1),
                Format = StencilFormat,
                Usage = TextureUsage.RenderAttachment,
                MipLevelCount = 1,
                SampleCount = 1,
                Dimension = TextureDimension.D2,
            });
            _onscreenStencilView = _onscreenStencil!.CreateView();
        }
        _targetWidth = width;
        _targetHeight = height;
        _vertexCursor = 0;
        _indexCursor = 0;
        _uniformCursor = 0;
    }

    /// <summary>Detach from the frame encoder (the host submits it).</summary>
    public void EndFrame()
    {
        _encoder = null;
        _onscreenColor = null;
    }

    // ---- global::Noesis.RenderDevice ----

    public override global::Noesis.DeviceCaps Caps => new()
    {
        CenterPixelOffset = 0f,
        LinearRendering = false,
        SubpixelRendering = false,
        DepthRangeZeroToOne = true,
        ClipSpaceYInverted = false,
    };

    public override global::Noesis.RenderTarget CreateRenderTarget(string label, uint width, uint height, uint sampleCount, bool needsPingPong)
    {
        if (sampleCount > 1) Unsupported.Add($"MSAA x{sampleCount} (rendered 1x)");
        var color = CreateNativeTexture($"{label}.Color", width, height, 1, global::Noesis.TextureFormat.RGBA8, renderTarget: true);
        var stencil = _device.CreateTexture(new TextureDescriptor
        {
            Label = $"{label}.Stencil",
            Size = new Extent3D(width, height, 1),
            Format = StencilFormat,
            Usage = TextureUsage.RenderAttachment,
            MipLevelCount = 1,
            SampleCount = 1,
            Dimension = TextureDimension.D2,
        })!;
        return new NoesisRenderTarget(color, stencil, stencil.CreateView()!);
    }

    public override global::Noesis.RenderTarget CloneRenderTarget(string label, global::Noesis.RenderTarget surface)
    {
        // Same size, fresh color, SHARED stencil (the reference devices share it too).
        var source = (NoesisRenderTarget)surface;
        var color = CreateNativeTexture($"{label}.Color", source.Color.W, source.Color.H, 1, global::Noesis.TextureFormat.RGBA8, renderTarget: true);
        return new NoesisRenderTarget(color, source.Stencil, source.StencilView);
    }

    public override void SetRenderTarget(global::Noesis.RenderTarget surface)
    {
        EndActivePass();
        _activeSurface = (NoesisRenderTarget)surface;
        var target = _activeSurface;
        var colors = new RenderPassColorAttachment[]
        {
            new()
            {
                View = target.Color.View,
                LoadOp = LoadOp.Clear,
                StoreOp = StoreOp.Store,
                ClearValue = new WebGpuSharp.Color(0, 0, 0, 0),
                DepthSlice = null,
            },
        };
        var passDesc = new RenderPassDescriptor
        {
            Label = "global::Noesis.Offscreen",
            ColorAttachments = colors,
            DepthStencilAttachment = new RenderPassDepthStencilAttachment
            {
                View = target.StencilView,
                StencilLoadOp = LoadOp.Clear,
                StencilStoreOp = StoreOp.Discard,
                StencilClearValue = 0,
            },
        };
        _pass = _encoder!.Value.BeginRenderPass(in passDesc);
        _stencilRef = byte.MaxValue;
    }

    public override void BeginTile(global::Noesis.RenderTarget surface, global::Noesis.Tile tile)
    {
        // Tile origin is bottom-left in Noesis; WebGPU scissor is top-left.
        var target = (NoesisRenderTarget)surface;
        var y = target.Color.H - (tile.Y + tile.Height);
        _pass!.Value.SetScissorRect(tile.X, y, tile.Width, tile.Height);
    }

    public override void EndTile(global::Noesis.RenderTarget surface)
        => _pass!.Value.SetScissorRect(0, 0, ((NoesisRenderTarget)surface).Color.W, ((NoesisRenderTarget)surface).Color.H);

    public override void ResolveRenderTarget(global::Noesis.RenderTarget surface, global::Noesis.Tile[] tiles) => EndActivePass();

    public override void BeginOffscreenRender() { }

    public override void EndOffscreenRender() => EndActivePass();

    public override void BeginOnscreenRender()
    {
        var colors = new RenderPassColorAttachment[]
        {
            new()
            {
                View = _onscreenColor ?? throw new InvalidOperationException("BeginFrame was not called."),
                LoadOp = LoadOp.Load, // composite over the scene
                StoreOp = StoreOp.Store,
                DepthSlice = null,
            },
        };
        var passDesc = new RenderPassDescriptor
        {
            Label = "global::Noesis.Onscreen",
            ColorAttachments = colors,
            DepthStencilAttachment = new RenderPassDepthStencilAttachment
            {
                View = _onscreenStencilView!,
                StencilLoadOp = LoadOp.Clear,
                StencilStoreOp = StoreOp.Discard,
                StencilClearValue = 0,
            },
        };
        _pass = _encoder!.Value.BeginRenderPass(in passDesc);
        _activeSurface = null;
        _stencilRef = byte.MaxValue;
    }

    public override void EndOnscreenRender() => EndActivePass();

    private void EndActivePass()
    {
        _pass?.End();
        _pass = null;
    }

    // ---- textures ----

    public override global::Noesis.Texture CreateTexture(string label, uint width, uint height, uint numLevels, global::Noesis.TextureFormat format, IntPtr data)
    {
        var texture = CreateNativeTexture(label, width, height, numLevels, format);
        if (data != IntPtr.Zero)
        {
            var w = width;
            var h = height;
            var offset = 0L;
            for (var level = 0u; level < numLevels; level++)
            {
                UploadLevel(texture, level, 0, 0, w, h, data + (nint)offset);
                offset += (long)w * h * BytesPerPixel(format);
                w = Math.Max(1, w / 2);
                h = Math.Max(1, h / 2);
            }
        }
        return texture;
    }

    public override void UpdateTexture(global::Noesis.Texture texture, uint level, uint x, uint y, uint width, uint height, IntPtr data)
        => UploadLevel((NoesisTexture)texture, level, x, y, width, height, data);

    private NoesisTexture CreateNativeTexture(string label, uint width, uint height, uint numLevels, global::Noesis.TextureFormat format, bool renderTarget = false)
    {
        var native = _device.CreateTexture(new TextureDescriptor
        {
            Label = label,
            Size = new Extent3D(width, height, 1),
            Format = format == global::Noesis.TextureFormat.R8 ? WebGpuSharp.TextureFormat.R8Unorm : WebGpuSharp.TextureFormat.RGBA8Unorm,
            Usage = TextureUsage.TextureBinding | TextureUsage.CopyDst | (renderTarget ? TextureUsage.RenderAttachment : default),
            MipLevelCount = numLevels,
            SampleCount = 1,
            Dimension = TextureDimension.D2,
        }) ?? throw new InvalidOperationException($"{label}: texture creation failed.");
        return new NoesisTexture(native, native.CreateView()!, width, height, format, numLevels > 1);
    }

    private unsafe void UploadLevel(NoesisTexture texture, uint level, uint x, uint y, uint width, uint height, IntPtr data)
    {
        var bpp = BytesPerPixel(texture.Format);
        var destination = new TexelCopyTextureInfo { Texture = texture.Native, MipLevel = level, Origin = new Origin3D(x, y, 0) };
        var layout = new TexelCopyBufferLayout { Offset = 0, BytesPerRow = width * bpp, RowsPerImage = height };
        var size = new Extent3D(width, height, 1);
        _queue.WriteTexture(destination, new ReadOnlySpan<byte>((void*)data, (int)(width * height * bpp)), layout, size);
    }

    private static uint BytesPerPixel(global::Noesis.TextureFormat format) => format == global::Noesis.TextureFormat.R8 ? 1u : 4u;

    // ---- geometry ----

    public override IntPtr MapVertices(uint bytes)
    {
        _mappedVertexBytes = bytes;
        return _vertexPin.AddrOfPinnedObject();
    }

    public override void UnmapVertices()
    {
        // Sub-allocate: WriteBuffer stages immediately and applies in queue order, so distinct
        // regions per map keep every already-recorded draw pointing at stable data.
        _vertexBase = _vertexCursor;
        if (_mappedVertexBytes > 0)
        {
            _queue.WriteBuffer(_vertexBuffer, _vertexBase, _vertexScratch.AsSpan(0, (int)_mappedVertexBytes));
            _vertexCursor = Align4(_vertexBase + _mappedVertexBytes);
        }
        _mappedVertexBytes = 0;
    }

    public override IntPtr MapIndices(uint bytes)
    {
        _mappedIndexBytes = bytes;
        return _indexPin.AddrOfPinnedObject();
    }

    public override void UnmapIndices()
    {
        _indexBase = _indexCursor;
        if (_mappedIndexBytes > 0)
        {
            _queue.WriteBuffer(_indexBuffer, _indexBase, _indexScratch.AsSpan(0, (int)_mappedIndexBytes));
            _indexCursor = Align4(_indexBase + _mappedIndexBytes);
        }
        _mappedIndexBytes = 0;
    }

    private static uint Align4(uint v) => (v + 3u) & ~3u;

    // ---- draw ----

    public override void DrawBatch(ref global::Noesis.Batch batch)
    {
        if (_pass is null) throw new InvalidOperationException("DrawBatch outside a render pass.");
        var variant = NoesisShaderCatalog.Variants[batch.Shader.Index];
        if (variant.Effect == NoesisShaderCatalog.Effect.Custom)
        {
            Unsupported.Add("Custom_Effect");
            return;
        }

        var pipeline = GetPipeline(variant, batch.RenderState);
        var vsSlot = WriteUniform(batch.VertexUniform0, batch.VertexUniform1);
        var ps0Slot = WriteUniform(batch.PixelUniform0, default);
        var ps1Slot = WriteUniform(batch.PixelUniform1, default, 512);
        var bindGroup = GetBindGroup(variant, ref batch, vsSlot, ps0Slot, ps1Slot);

        var pass = _pass!.Value;
        pass.SetPipeline(pipeline);
        // Slots already carry absolute offsets; dynamic offsets are zero-based against them.
        ReadOnlySpan<uint> offsets = [vsSlot, ps0Slot, ps1Slot];
        pass.SetBindGroup(0, bindGroup, offsets);
        if (_stencilRef != batch.StencilRef)
        {
            pass.SetStencilReference(batch.StencilRef);
            _stencilRef = batch.StencilRef;
        }
        pass.SetVertexBuffer(0, _vertexBuffer, _vertexBase + batch.VertexOffset, VertexBufferBytes - (_vertexBase + batch.VertexOffset));
        pass.SetIndexBuffer(_indexBuffer, WebGpuSharp.IndexFormat.Uint16, _indexBase, IndexBufferBytes - _indexBase);
        pass.DrawIndexed(batch.NumIndices, 1, batch.StartIndex, 0, 0);
    }

    private unsafe uint WriteUniform(in global::Noesis.UniformData first, in global::Noesis.UniformData second, uint slotBytes = 256)
    {
        var offset = _uniformCursor;
        _uniformCursor += Math.Max(slotBytes, UniformAlign);
        if (_uniformCursor > UniformRingBytes)
        {
            offset = 0;
            _uniformCursor = Math.Max(slotBytes, UniformAlign);
        }
        var scratch = _uniformScratch.AsSpan(0, (int)slotBytes);
        scratch.Clear();
        if (first.NumWords > 0 && first.Values != IntPtr.Zero)
        {
            new ReadOnlySpan<byte>((void*)first.Values, (int)Math.Min(first.NumWords * 4, slotBytes)).CopyTo(scratch);
        }
        if (second.NumWords > 0 && second.Values != IntPtr.Zero)
        {
            // Vertex cbuffer1 (SDF st1 scale) lands after the 64-byte projection.
            new ReadOnlySpan<byte>((void*)second.Values, (int)Math.Min(second.NumWords * 4, slotBytes - 64)).CopyTo(scratch[64..]);
        }
        _queue.WriteBuffer(_uniformBuffer, offset, scratch);
        return offset;
    }

    private BindGroup GetBindGroup(in NoesisShaderCatalog.Variant variant, ref global::Noesis.Batch batch, uint vsSlot, uint ps0Slot, uint ps1Slot)
    {
        var pattern = (NoesisTexture?)batch.Pattern ?? _dummyRgba;
        var ramps = (NoesisTexture?)batch.Ramps ?? _dummyRgba;
        var image = (NoesisTexture?)batch.Image ?? _dummyRgba;
        var glyphs = (NoesisTexture?)batch.Glyphs ?? _dummyR8;
        var shadow = (NoesisTexture?)batch.Shadow ?? _dummyR8;
        // One sampler binding: prefer the sampler state of the variant's primary texture.
        global::Noesis.SamplerState samplerState = default;
        if (variant.Paint is NoesisShaderCatalog.Paint.Linear or NoesisShaderCatalog.Paint.Radial)
            samplerState = batch.RampsSampler;
        else if (variant.Paint >= NoesisShaderCatalog.Paint.Pattern)
            samplerState = batch.PatternSampler;
        else if (variant.Effect == NoesisShaderCatalog.Effect.Sdf)
            samplerState = batch.GlyphsSampler;
        else if (variant.Effect is NoesisShaderCatalog.Effect.Opacity or NoesisShaderCatalog.Effect.Shadow
                 or NoesisShaderCatalog.Effect.Blur or NoesisShaderCatalog.Effect.Upsample)
            samplerState = batch.ImageSampler;
        var samplerByte = SamplerStateByte(samplerState);

        // Dynamic offsets make uniform slots part of SetBindGroup, so the cache key is only
        // resources. All three uniform bindings alias the ring buffer at offset 0.
        var key = new BindKey(0, 0, 0, pattern.Id, ramps.Id, image.Id, glyphs.Id, shadow.Id, samplerByte);
        if (_bindGroups.TryGetValue(key, out var cached)) return cached;

        var bindGroup = _device.CreateBindGroup(new BindGroupDescriptor
        {
            Label = "global::Noesis.BindGroup",
            Layout = _bindGroupLayout,
            Entries =
            [
                new BindGroupEntry { Binding = 0, Buffer = _uniformBuffer, Offset = 0, Size = 80 },
                new BindGroupEntry { Binding = 1, Buffer = _uniformBuffer, Offset = 0, Size = 32 },
                new BindGroupEntry { Binding = 2, Buffer = _uniformBuffer, Offset = 0, Size = 512 },
                new BindGroupEntry { Binding = 3, TextureView = pattern.View },
                new BindGroupEntry { Binding = 4, TextureView = ramps.View },
                new BindGroupEntry { Binding = 5, TextureView = image.View },
                new BindGroupEntry { Binding = 6, TextureView = glyphs.View },
                new BindGroupEntry { Binding = 7, TextureView = shadow.View },
                new BindGroupEntry { Binding = 8, Sampler = GetSampler(samplerByte) },
            ],
        }) ?? throw new InvalidOperationException("Noesis bind group creation failed.");
        _bindGroups[key] = bindGroup;
        return bindGroup;
    }

    private static byte SamplerStateByte(in global::Noesis.SamplerState state)
        => (byte)((int)state.WrapMode | ((int)state.MinMagFilter << 3) | ((int)state.MipFilter << 4));

    private Sampler GetSampler(byte key)
    {
        if (_samplers[key] is { } cached) return cached;
        var wrap = (global::Noesis.WrapMode)(key & 0b111);
        var minMag = (global::Noesis.MinMagFilter)((key >> 3) & 1);
        var mip = (global::Noesis.MipFilter)((key >> 4) & 0b11);
        var (u, v) = wrap switch
        {
            global::Noesis.WrapMode.ClampToEdge or global::Noesis.WrapMode.ClampToZero => (AddressMode.ClampToEdge, AddressMode.ClampToEdge),
            global::Noesis.WrapMode.Repeat => (AddressMode.Repeat, AddressMode.Repeat),
            global::Noesis.WrapMode.MirrorU => (AddressMode.MirrorRepeat, AddressMode.Repeat),
            global::Noesis.WrapMode.MirrorV => (AddressMode.Repeat, AddressMode.MirrorRepeat),
            _ => (AddressMode.MirrorRepeat, AddressMode.MirrorRepeat),
        };
        var filter = minMag == global::Noesis.MinMagFilter.Linear ? FilterMode.Linear : FilterMode.Nearest;
        var sampler = _device.CreateSampler(new SamplerDescriptor
        {
            Label = "global::Noesis.Sampler",
            AddressModeU = u,
            AddressModeV = v,
            AddressModeW = AddressMode.ClampToEdge,
            MinFilter = filter,
            MagFilter = filter,
            MipmapFilter = mip switch
            {
                global::Noesis.MipFilter.Linear => MipmapFilterMode.Linear,
                global::Noesis.MipFilter.Nearest => MipmapFilterMode.Nearest,
                _ => MipmapFilterMode.Nearest,
            },
        }) ?? throw new InvalidOperationException("Noesis sampler creation failed.");
        _samplers[key] = sampler;
        return sampler;
    }

    // ---- pipelines ----

    /// <summary>Compile every supported shader variant against the common render states so
    /// first use never hitches (and tests validate all WGSL against the backend).</summary>
    public int PrewarmPipelines()
    {
        var count = 0;
        foreach (var variant in NoesisShaderCatalog.Variants)
        {
            if (variant.Effect == NoesisShaderCatalog.Effect.Custom) continue;
            GetPipeline(variant, global::Noesis.BlendMode.SrcOver, global::Noesis.StencilMode.Disabled, colorEnable: true);
            GetPipeline(variant, global::Noesis.BlendMode.SrcOver, global::Noesis.StencilMode.Equal_Keep, colorEnable: true);
            count += 2;
        }
        // The stencil-writing states used by masking.
        var mask = NoesisShaderCatalog.Variants[1];
        var clear = NoesisShaderCatalog.Variants[2];
        GetPipeline(mask, global::Noesis.BlendMode.SrcOver, global::Noesis.StencilMode.Equal_Incr, colorEnable: false);
        GetPipeline(mask, global::Noesis.BlendMode.SrcOver, global::Noesis.StencilMode.Equal_Decr, colorEnable: false);
        GetPipeline(clear, global::Noesis.BlendMode.SrcOver, global::Noesis.StencilMode.Clear, colorEnable: false);
        return count + 3;
    }

    private RenderPipeline GetPipeline(in NoesisShaderCatalog.Variant variant, in global::Noesis.RenderState state)
    {
        var blend = state.BlendMode;
        if (blend == global::Noesis.BlendMode.SrcOver_Dual)
        {
            Unsupported.Add("SrcOver_Dual (fell back to SrcOver)");
            blend = global::Noesis.BlendMode.SrcOver;
        }
        return GetPipeline(variant, blend, state.StencilMode, state.ColorEnable);
    }

    private RenderPipeline GetPipeline(in NoesisShaderCatalog.Variant variant, global::Noesis.BlendMode blend, global::Noesis.StencilMode stencilMode, bool colorEnable)
    {
        var key = new PipelineKey(variant.Index, blend, stencilMode, colorEnable);
        if (_pipelines.TryGetValue(key, out var cached)) return cached;

        var wgsl = NoesisShaderCatalog.GenerateWgsl(variant);
        var moduleDesc = new ShaderModuleWGSLDescriptor { Code = wgsl };
        var module = _device.CreateShaderModuleWGSL(variant.Name, in moduleDesc)
            ?? throw new InvalidOperationException($"{variant.Name}: WGSL compile failed.");

        // Interleaved attributes with SEQUENTIAL shader locations (must match GenerateWgsl).
        var attributes = new List<VertexAttribute>();
        var offset = 0u;
        var location = 0u;
        foreach (var (attr, size) in NoesisShaderCatalog.AttrSizes)
        {
            if ((variant.Attrs & attr) == 0) continue;
            attributes.Add(new VertexAttribute
            {
                Format = attr switch
                {
                    NoesisShaderCatalog.Attr.Pos or NoesisShaderCatalog.Attr.Tex0 or NoesisShaderCatalog.Attr.Tex1 => VertexFormat.Float32x2,
                    NoesisShaderCatalog.Attr.Color => VertexFormat.Unorm8x4,
                    NoesisShaderCatalog.Attr.Coverage => VertexFormat.Float32,
                    NoesisShaderCatalog.Attr.Rect => VertexFormat.Unorm16x4,
                    _ => VertexFormat.Float32x4,
                },
                Offset = offset,
                ShaderLocation = location++,
            });
            offset += (uint)size;
        }
        var vertexLayout = new VertexBufferLayout
        {
            ArrayStride = (ulong)variant.Stride,
            StepMode = VertexStepMode.Vertex,
            Attributes = attributes.ToArray(),
        };

        var colorTargets = new ColorTargetState[]
        {
            new()
            {
                Format = _colorFormat,
                Blend = BlendFor(blend),
                WriteMask = colorEnable ? ColorWriteMask.All : ColorWriteMask.None,
            },
        };
        var (compare, passOp, writeMask) = stencilMode switch
        {
            global::Noesis.StencilMode.Equal_Keep or global::Noesis.StencilMode.Equal_Keep_ZTest => (CompareFunction.Equal, StencilOperation.Keep, 0u),
            global::Noesis.StencilMode.Equal_Incr => (CompareFunction.Equal, StencilOperation.IncrementClamp, 0xFFu),
            global::Noesis.StencilMode.Equal_Decr => (CompareFunction.Equal, StencilOperation.DecrementClamp, 0xFFu),
            global::Noesis.StencilMode.Clear => (CompareFunction.Always, StencilOperation.Zero, 0xFFu),
            _ => (CompareFunction.Always, StencilOperation.Keep, 0u), // Disabled(+ZTest)
        };

        var pipelineDesc = new RenderPipelineDescriptor
        {
            Label = variant.Name,
            Layout = _pipelineLayout,
            Vertex = new VertexState
            {
                Module = module,
                EntryPoint = "vs_main",
                Buffers = new WebGpuManagedSpan<VertexBufferLayout>(new[] { vertexLayout }),
            },
            Fragment = new FragmentState
            {
                Module = module,
                EntryPoint = "fs_main",
                Targets = new WebGpuManagedSpan<ColorTargetState>(colorTargets),
            },
            Primitive = new PrimitiveState { Topology = PrimitiveTopology.TriangleList },
            Multisample = new MultisampleState { Count = 1, Mask = uint.MaxValue },
            DepthStencil = new DepthStencilState
            {
                Format = StencilFormat,
                DepthWriteEnabled = OptionalBool.False,
                DepthCompare = CompareFunction.Undefined,
                StencilFront = new StencilFaceState { Compare = compare, FailOp = StencilOperation.Keep, DepthFailOp = StencilOperation.Keep, PassOp = passOp },
                StencilBack = new StencilFaceState { Compare = compare, FailOp = StencilOperation.Keep, DepthFailOp = StencilOperation.Keep, PassOp = passOp },
                StencilReadMask = 0xFF,
                StencilWriteMask = writeMask,
            },
        };
        var pipeline = _device.CreateRenderPipelineSync(in pipelineDesc)
            ?? throw new InvalidOperationException($"{variant.Name}: pipeline creation failed.");
        _pipelines[key] = pipeline;
        return pipeline;
    }

    private static BlendState? BlendFor(global::Noesis.BlendMode mode) => mode switch
    {
        global::Noesis.BlendMode.Src => null, // replace
        global::Noesis.BlendMode.SrcOver_Multiply => Blend(BlendFactor.Dst, BlendFactor.OneMinusSrcAlpha),
        global::Noesis.BlendMode.SrcOver_Screen => Blend(BlendFactor.One, BlendFactor.OneMinusSrc),
        global::Noesis.BlendMode.SrcOver_Additive => Blend(BlendFactor.One, BlendFactor.One),
        _ => Blend(BlendFactor.One, BlendFactor.OneMinusSrcAlpha), // SrcOver (premultiplied)
    };

    private static BlendState Blend(BlendFactor src, BlendFactor dst) => new()
    {
        Color = new BlendComponent { Operation = BlendOperation.Add, SrcFactor = src, DstFactor = dst },
        Alpha = new BlendComponent { Operation = BlendOperation.Add, SrcFactor = BlendFactor.One, DstFactor = BlendFactor.OneMinusSrcAlpha },
    };

    /// <summary>Free the pinned map buffers, then the base component.</summary>
    public new void Dispose()
    {
        if (_vertexPin.IsAllocated) _vertexPin.Free();
        if (_indexPin.IsAllocated) _indexPin.Free();
        base.Dispose();
    }
}
