namespace Paradise.ECS;

/// <summary>
/// Interface for queryable data types that provide per-entity component access.
/// Implementations are generated by the source generator for each [Queryable] type.
/// </summary>
/// <typeparam name="TSelf">The implementing type (CRTP pattern).</typeparam>
/// <typeparam name="TMask">The component mask type implementing IBitSet.</typeparam>
/// <typeparam name="TConfig">The world configuration type.</typeparam>
public interface IQueryData<TSelf, TMask, TConfig>
    where TSelf : IQueryData<TSelf, TMask, TConfig>, allows ref struct
    where TMask : unmanaged, IBitSet<TMask>
    where TConfig : IConfig, new()
{
    /// <summary>
    /// Creates a new instance of the data type for the specified entity location.
    /// </summary>
    /// <param name="chunkManager">The chunk manager for memory access.</param>
    /// <param name="entityManager">The entity manager for looking up entity versions.</param>
    /// <param name="layout">The archetype layout describing component offsets.</param>
    /// <param name="chunk">The chunk handle containing the entity.</param>
    /// <param name="indexInChunk">The entity's index within the chunk.</param>
    /// <returns>A new data instance providing component access.</returns>
    static abstract TSelf Create(
        ChunkManager chunkManager,
        IEntityManager entityManager,
        ImmutableArchetypeLayout<TMask, TConfig> layout,
        ChunkHandle chunk,
        int indexInChunk);

    /// <summary>
    /// Whether one matched row actually belongs to this query — the hook for constraints an
    /// ARCHETYPE mask cannot express.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Defaults to true, and virtually all queryables leave it there: archetype matching already
    /// answered the question, and a row-by-row test would be pure cost. The generator overrides it
    /// for a queryable declaring <c>[WithTag&lt;T&gt;]</c>, where the deciding bits live in the
    /// entity's <c>EntityTags</c> component rather than in its archetype, precisely so that adding
    /// or removing a tag does not move the entity between archetypes.
    /// </para>
    /// <para>
    /// A static VIRTUAL with a body, not an abstract: every queryable already generated by every
    /// consumer keeps satisfying this interface untouched. And because <c>TSelf</c> is a struct
    /// type parameter the call is devirtualized, so the default folds away entirely at the call
    /// sites in <see cref="QueryResult{TData,TArchetype,TMask,TConfig}"/>.
    /// </para>
    /// </remarks>
    /// <param name="chunkManager">The chunk manager for memory access.</param>
    /// <param name="layout">The archetype layout describing component offsets.</param>
    /// <param name="chunk">The chunk handle containing the entity.</param>
    /// <param name="indexInChunk">The entity's index within the chunk.</param>
    /// <returns>True to yield the row; false to skip it.</returns>
    static virtual bool Matches(
        ChunkManager chunkManager,
        ImmutableArchetypeLayout<TMask, TConfig> layout,
        ChunkHandle chunk,
        int indexInChunk) => true;

    /// <summary>
    /// Whether <see cref="Matches"/> can ever answer false — i.e. whether archetype matching is the
    /// whole story for this queryable.
    /// </summary>
    /// <remarks>
    /// It exists so that counting stays honest without making it slow. A query with no row filter
    /// knows its size from archetype bookkeeping alone, in constant time; a filtered one cannot,
    /// and has to walk its rows. Branching on this constant keeps the first case exactly as fast as
    /// it was — the JIT sees a literal false through the struct type parameter and drops the walk
    /// entirely — while stopping the second from reporting the number of rows it would have
    /// yielded had it not been filtering.
    /// </remarks>
    static virtual bool IsFiltered => false;

    /// <summary>
    /// Whether a whole CHUNK can be passed over without inspecting any of its rows.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The coarse half of <see cref="Matches"/>. Where that answers "does this row belong", this
    /// answers "could anything in this chunk belong" — so a false lets the enumerator skip the
    /// chunk entirely rather than testing every entity in it, which is the difference between
    /// O(entities in matching archetypes) and O(entities that might match).
    /// </para>
    /// <para>
    /// It must be CONSERVATIVE: returning true for a chunk holding nothing of interest merely
    /// wastes the row tests that follow, but returning false for a chunk that holds a match makes
    /// that entity vanish from the query. Implementations therefore answer from a summary that is
    /// allowed to over-report and never to under-report — for tags, the chunk's union mask, which
    /// gains bits on add and keeps them on remove for exactly that reason.
    /// </para>
    /// <para>
    /// Defaults to true, and the default folds away through the struct type parameter, so a
    /// queryable that declares no chunk-level constraint pays nothing.
    /// </para>
    /// </remarks>
    /// <param name="chunkManager">The chunk manager for memory access.</param>
    /// <param name="layout">The archetype layout describing component and aggregate offsets.</param>
    /// <param name="chunk">The chunk being considered.</param>
    /// <returns>False only when the chunk provably contains no match.</returns>
    static virtual bool ChunkMatches(
        ChunkManager chunkManager,
        ImmutableArchetypeLayout<TMask, TConfig> layout,
        ChunkHandle chunk) => true;
}

/// <summary>
/// Interface for queryable chunk data types that provide batch component access via spans.
/// Implementations are generated by the source generator for each [Queryable] type.
/// </summary>
/// <typeparam name="TSelf">The implementing type (CRTP pattern).</typeparam>
/// <typeparam name="TMask">The component mask type implementing IBitSet.</typeparam>
/// <typeparam name="TConfig">The world configuration type.</typeparam>
public interface IQueryChunkData<TSelf, TMask, TConfig>
    where TSelf : IQueryChunkData<TSelf, TMask, TConfig>, allows ref struct
    where TMask : unmanaged, IBitSet<TMask>
    where TConfig : IConfig, new()
{
    /// <summary>
    /// Creates a new instance of the chunk data type for the specified chunk.
    /// </summary>
    /// <param name="chunkManager">The chunk manager for memory access.</param>
    /// <param name="entityManager">The entity manager for looking up entity versions.</param>
    /// <param name="layout">The archetype layout describing component offsets.</param>
    /// <param name="chunk">The chunk handle.</param>
    /// <param name="entityCount">The number of entities in this chunk.</param>
    /// <returns>A new chunk data instance providing span-based component access.</returns>
    static abstract TSelf Create(
        ChunkManager chunkManager,
        IEntityManager entityManager,
        ImmutableArchetypeLayout<TMask, TConfig> layout,
        ChunkHandle chunk,
        int entityCount);
}
