<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Paradise.Cli.Extensibility/Paradise.Cli.Extensibility.csproj" Private="false" ExcludeAssets="runtime" />
    <ProjectReference Include="../Paradise.Assets.Pipeline/Paradise.Assets.Pipeline.csproj" Private="false" ExcludeAssets="runtime" />
    <ProjectReference Include="../Paradise.Cli.Test.PluginDependency/Paradise.Cli.Test.PluginDependency.csproj" />
  </ItemGroup>
</Project>
